/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ClsConexion;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Will Vásquez
 */
public class frmCredito extends javax.swing.JDialog {
    ClsConexion cc = new ClsConexion();
    Connection cn = cc.conectar();
    private PreparedStatement st;
    DefaultTableModel modelo;
    DecimalFormat df = new DecimalFormat("0.00");

    /**
     * Creates new form frmCredito
     */
    public frmCredito(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Gestor ventas al crédito");
        getContentPane().setBackground(Color.DARK_GRAY);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcodigo = new javax.swing.JTextField();
        txtdui = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbempleado = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbfecha = new org.freixas.jcalendar.JCalendarCombo();
        jLabel3 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfardos = new javax.swing.JTextField();
        txtpromo = new javax.swing.JTextField();
        txtentrego = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdebe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbestado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcomentarios = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        cmbrecibido = new javax.swing.JComboBox<>();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        jLabel11 = new javax.swing.JLabel();
        txtcontacto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablacre = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Empleado:");

        cmbempleado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbempleadoItemStateChanged(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cliente:");

        txtcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtclienteKeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fardos:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Promoción:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Entregó ($):");

        txtfardos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfardosKeyTyped(evt);
            }
        });

        txtpromo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpromoKeyTyped(evt);
            }
        });

        txtentrego.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtentrego.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtentregoFocusLost(evt);
            }
        });
        txtentrego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtentregoActionPerformed(evt);
            }
        });
        txtentrego.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtentregoKeyTyped(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Debe (?):");

        txtdebe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdebe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdebeFocusLost(evt);
            }
        });
        txtdebe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdebeKeyTyped(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estado:");

        cmbestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cancelado", "Pendiente" }));
        cmbestado.setSelectedIndex(-1);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Comentarios:");

        txtcomentarios.setColumns(20);
        txtcomentarios.setLineWrap(true);
        txtcomentarios.setRows(2);
        jScrollPane1.setViewportView(txtcomentarios);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Recibido por:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contacto:");

        txtcontacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcontactoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfardos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(panelCurves1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(28, 28, 28)
                            .addComponent(txtpromo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbestado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbrecibido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtentrego, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(txtdebe))
                    .addComponent(txtcontacto))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtentrego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtdebe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtcontacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cmbestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtfardos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cmbrecibido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtpromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/agregar.png"))); // NOI18N
        btnguardar.setText("Guardar datos");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/edit.png"))); // NOI18N
        btnmodificar.setText("Modificar datos");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btnconsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/consultar.png"))); // NOI18N
        btnconsultar.setText("Consultar datos");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/eliminar.png"))); // NOI18N
        btneliminar.setText("Eliminar datos");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/limpiar.png"))); // NOI18N
        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnconsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnguardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmodificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnconsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btneliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablacre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablacre.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablacre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacreMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablacre);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Consulta avanzada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Buscar por cliente o estado:");

        txtbuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(txtbuscar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CargarEmpleados();
        CargarAdmin();
        bloquear();
        limpiar();
    }//GEN-LAST:event_formWindowOpened

    private void cmbempleadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbempleadoItemStateChanged
        if(cmbempleado.getSelectedIndex() > -1){
            cmbfecha.setEnabled(true);
            txtbuscar.setEnabled(true);
            txtcliente.setEnabled(true);
            txtfardos.setEnabled(true);
            txtpromo.setEnabled(true);
            txtentrego.setEnabled(true);
            txtdebe.setEnabled(true);
            txtcontacto.setEnabled(true);
            cmbestado.setEnabled(true);
            cmbrecibido.setEnabled(true);
            txtcomentarios.setEnabled(true);
            limpiar2();
            tablacre.setModel(new DefaultTableModel());
            try {
                st = cn.prepareStatement("SELECT id_emp FROM empleados WHERE nom_emp = ?");
                st.setString(1, cmbempleado.getSelectedItem().toString());
                ResultSet rs2 = st.executeQuery();
                rs2.next();
                int admin2 = rs2.getInt(1);
                txtdui.setText(String.valueOf(admin2));
            } catch (Exception e) { 
                JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cmbempleadoItemStateChanged

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        if (cmbempleado.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un empleado para realizar la consulta", "AVISO", JOptionPane.CANCEL_OPTION);
        } else {
            MostrarDatos(Integer.parseInt(txtdui.getText()));
        }
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if (cmbempleado.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "¡Debes seleccionar un empleado!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if(txtcliente.getText().isEmpty() || txtfardos.getText().isEmpty() || txtpromo.getText().isEmpty() || txtentrego.getText().isEmpty() || txtcontacto.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "¡No puedes dejar campos en blanco!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if (cmbrecibido.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "¿Quién ha recibido la venta?", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if (cmbestado.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "¡Debes seleccionar un estado!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if (txtentrego.getText() == "0.0") {
            JOptionPane.showMessageDialog(this, "¡No puede haber cantidades de cero!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else{
            try {
                st = cn.prepareStatement("SELECT id_emp FROM empleados WHERE nom_emp = ?");
                st.setString(1, cmbempleado.getSelectedItem().toString());
                ResultSet rs = st.executeQuery();
                if (rs.next()) {
                    String empleado = rs.getString(1);
                    st = cn.prepareStatement("SELECT id_admin FROM administradores WHERE nom_admin = ?");
                    st.setString(1, cmbrecibido.getSelectedItem().toString());
                    ResultSet rs2 = st.executeQuery();
                    if (rs2.next()) {
                        String admin = rs2.getString(1);
                        if (txtcomentarios.getText().isEmpty()) {
                            st = cn.prepareStatement("INSERT INTO credito(fecha_credito, cant_fardos_credito, promo_credito, "
                                    + "cant_a_entr_cred, cliente_credito, tel_cliente_credito, debe_cliente_credito, estado_credito, "
                                    + "coment_credito, id_admin, id_emp) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                            java.sql.Date sqlFecha = new java.sql.Date(cmbfecha.getDate().getTime());
                            st.setDate(1, sqlFecha);
                            st.setInt(2, Integer.parseInt(txtfardos.getText()));
                            st.setString(3, txtpromo.getText());
                            st.setDouble(4, Double.parseDouble(txtentrego.getText()));
                            st.setString(5, txtcliente.getText());
                            st.setString(6, txtcontacto.getText());
                            st.setDouble(7, Double.parseDouble(txtdebe.getText()));
                            st.setString(8, cmbestado.getSelectedItem().toString());
                            st.setString(9, "No hay comentarios.");
                            st.setInt(10, Integer.parseInt(admin));
                            st.setInt(11, Integer.parseInt(empleado));
                            st.executeUpdate();
                            JOptionPane.showMessageDialog(rootPane, "Datos guardados con éxito");
                            bloquear();
                            MostrarDatos(Integer.parseInt(txtdui.getText()));
                            limpiar();
                            tablacre.setModel(new DefaultTableModel());
                        }else{
                           st = cn.prepareStatement("INSERT INTO credito(fecha_credito, cant_fardos_credito, promo_credito, "
                                    + "cant_a_entr_cred, cliente_credito, tel_cliente_credito, debe_cliente_credito, estado_credito, "
                                    + "coment_credito, id_admin, id_emp) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                            java.sql.Date sqlFecha = new java.sql.Date(cmbfecha.getDate().getTime());
                            st.setDate(1, sqlFecha);
                            st.setInt(2, Integer.parseInt(txtfardos.getText()));
                            st.setString(3, txtpromo.getText());
                            st.setDouble(4, Double.parseDouble(txtentrego.getText()));
                            st.setString(5, txtcliente.getText());
                            st.setString(6, txtcontacto.getText());
                            st.setDouble(7, Double.parseDouble(txtdebe.getText()));
                            st.setString(8, cmbestado.getSelectedItem().toString());
                            st.setString(9, txtcomentarios.getText());
                            st.setInt(10, Integer.parseInt(admin));
                            st.setInt(11, Integer.parseInt(empleado));
                            st.executeUpdate();
                            JOptionPane.showMessageDialog(rootPane, "Datos guardados con éxito");
                            bloquear();
                            MostrarDatos(Integer.parseInt(txtdui.getText()));
                            limpiar();
                            tablacre.setModel(new DefaultTableModel()); 
                        }
                    }
                }
            } catch (SQLException | NumberFormatException e) {JOptionPane.showMessageDialog(this, "Error: " + e, "ERROR", JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        bloquear();
        limpiar();
        tablacre.setModel(new DefaultTableModel());
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void tablacreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacreMouseClicked
        try {
            txtcodigo.setText(tablacre.getValueAt(tablacre.getSelectedRow(), 0).toString());
            SimpleDateFormat Formateador = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date fecha = Formateador.parse(tablacre.getValueAt(tablacre.getSelectedRow(), 1).toString());
            cmbfecha.setSelectedIndex(-1);
            cmbfecha.setDate(fecha);
            txtcliente.setText(tablacre.getValueAt(tablacre.getSelectedRow(), 2).toString());
            txtfardos.setText(tablacre.getValueAt(tablacre.getSelectedRow(), 3).toString());
            txtpromo.setText(tablacre.getValueAt(tablacre.getSelectedRow(), 4).toString());
            txtentrego.setText(tablacre.getValueAt(tablacre.getSelectedRow(), 5).toString());
            txtdebe.setText(tablacre.getValueAt(tablacre.getSelectedRow(), 6).toString());
            txtcontacto.setText(tablacre.getValueAt(tablacre.getSelectedRow(), 7).toString());
            cmbestado.setSelectedItem(tablacre.getValueAt(tablacre.getSelectedRow(), 8));
            cmbrecibido.setSelectedItem(tablacre.getValueAt(tablacre.getSelectedRow(), 9));
            txtcomentarios.setText(tablacre.getValueAt(tablacre.getSelectedRow(), 10).toString());
        } catch (Exception e) {JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_tablacreMouseClicked

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        if("".equals(txtcodigo.getText())){
            JOptionPane.showMessageDialog(this, "¡No puedes dejar campos en blanco!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if(cmbempleado.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(this, "¡Debes seleccionar un empleado!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if(txtcliente.getText().isEmpty() || txtfardos.getText().isEmpty() || txtpromo.getText().isEmpty() || txtcontacto.getText().isEmpty() || txtentrego.getText().isEmpty() || txtcomentarios.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "¡No puedes dejar campos en blanco!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if(cmbestado.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(this, "¡Debes seleccionar un estado!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if(cmbrecibido.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(this, "¡Debes seleccionar quién lo recibió!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else{
            try {
                st = cn.prepareStatement("SELECT id_emp FROM empleados WHERE nom_emp = ?");
                st.setString(1, cmbempleado.getSelectedItem().toString());
                ResultSet rs = st.executeQuery();
                if (rs.next()) {
                    String empleado = rs.getString(1);
                    st = cn.prepareStatement("SELECT id_admin FROM administradores WHERE nom_admin = ?");
                    st.setString(1, cmbrecibido.getSelectedItem().toString());
                    ResultSet rs2 = st.executeQuery();
                    if (rs2.next()) {
                        String admin = rs2.getString(1);
                        st = cn.prepareStatement("UPDATE credito SET fecha_credito = ?, cant_fardos_credito = ?, promo_credito = ?, "
                            + "cant_a_entr_cred = ?, cliente_credito = ?, tel_cliente_credito = ?, debe_cliente_credito = ?, estado_credito = ?, "
                            + "coment_credito = ?, id_admin = ?, id_emp = ? WHERE id_credito = ?");
                        java.sql.Date sqlFecha = new java.sql.Date(cmbfecha.getDate().getTime());
                            st.setDate(1, sqlFecha);
                            st.setInt(2, Integer.parseInt(txtfardos.getText()));
                            st.setString(3, txtpromo.getText());
                            st.setDouble(4, Double.parseDouble(txtentrego.getText()));
                            st.setString(5, txtcliente.getText());
                            st.setString(6, txtcontacto.getText());
                            st.setDouble(7, Double.parseDouble(txtdebe.getText()));
                            st.setString(8, cmbestado.getSelectedItem().toString());
                            st.setString(9, txtcomentarios.getText());
                            st.setInt(10, Integer.parseInt(admin));
                            st.setInt(11, Integer.parseInt(empleado));
                            st.setInt(12, Integer.parseInt(txtcodigo.getText()));
                            st.executeUpdate();
                            JOptionPane.showMessageDialog(rootPane, "Datos modificados con éxito");
                            MostrarDatos(Integer.parseInt(txtdui.getText()));
                            limpiar2();
                    }
                }
            } catch (SQLException | NumberFormatException e) {JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if("".equals(txtcodigo.getText())){
            JOptionPane.showMessageDialog(this, "¡Debes realizar y seleccionar una consulta para eliminar!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else{
            try {
                st = cn.prepareStatement("DELETE FROM credito WHERE id_credito = ?");
                st.setInt(1, Integer.parseInt(txtcodigo.getText()));
                if(JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro que desea eliminar estos datos?" + "\n¡Ya no podrán ser recuperados!", "Confirmación", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "Datos eliminados con éxito");
                    MostrarDatos(Integer.parseInt(txtdui.getText()));
                    bloquear();
                    limpiar();
                    cmbempleado.setSelectedIndex(-1);
                }
            } catch (SQLException | NumberFormatException | HeadlessException e) {JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtfardosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfardosKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || txtfardos.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_txtfardosKeyTyped

    private void txtentregoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtentregoKeyTyped
        try {
            if (!Character.isDigit(evt.getKeyChar()) && !(evt.getKeyChar() == '.') || txtentrego.getText().length() >= 7) {
                evt.consume();
            }
            Double.parseDouble(txtentrego.getText() + evt.getKeyChar());
        } catch (NumberFormatException e) {
            evt.consume();
        }
    }//GEN-LAST:event_txtentregoKeyTyped

    private void txtdebeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdebeKeyTyped
        try {
            if (!Character.isDigit(evt.getKeyChar()) && !(evt.getKeyChar() == '.') || txtdebe.getText().length() >= 7) {
                evt.consume();
            }
            Double.parseDouble(txtdebe.getText() + evt.getKeyChar());
        } catch (NumberFormatException e) {
            evt.consume();
        }
    }//GEN-LAST:event_txtdebeKeyTyped

    private void txtentregoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtentregoFocusLost
        if (txtentrego.getText().isEmpty()) {
            txtentrego.setText("0.0");
        } else {
            String precio = df.format(Double.parseDouble(txtentrego.getText()));
            precio = precio.replaceAll(",", ".");
            try {
                txtentrego.setText(precio);
            } catch (NumberFormatException e) {
                txtentrego.setText(null);
            }
        }
    }//GEN-LAST:event_txtentregoFocusLost

    private void txtdebeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdebeFocusLost
        if (txtdebe.getText().isEmpty()) {
            txtdebe.setText("0.0");
        } else {
            String precio = df.format(Double.parseDouble(txtdebe.getText()));
            precio = precio.replaceAll(",", ".");
            try {
                txtdebe.setText(precio);
            } catch (NumberFormatException e) {
                txtdebe.setText(null);
            }
        }
    }//GEN-LAST:event_txtdebeFocusLost

    private void txtclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclienteKeyTyped
        if (txtcliente.getText().length() >= 75) {
            evt.consume();
        }
    }//GEN-LAST:event_txtclienteKeyTyped

    private void txtpromoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpromoKeyTyped
        if (txtpromo.getText().length() >= 25) {
            evt.consume();
        }
    }//GEN-LAST:event_txtpromoKeyTyped

    private void txtcontactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontactoKeyTyped
        if (txtcontacto.getText().length() >= 75) {
            evt.consume();
        }
    }//GEN-LAST:event_txtcontactoKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(null, "ATENCIÓN" + "\nLe recomendamos que verifique si ha ingresado correctamente los datos de este día" + "\nDicho esto, ¿Desea cerrar la ventana?", "AVISO", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
        }else{
            dispose();
            frmCredito obj = new frmCredito(null, true);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        if(txtbuscar.getText().isEmpty()){
            tablacre.setModel(new DefaultTableModel());
        }else{
            BuscarCliente(txtbuscar.getText(), Integer.parseInt(txtdui.getText()));
        }
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void txtentregoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtentregoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtentregoActionPerformed

    private void bloquear(){
        cmbfecha.setEnabled(false);
        txtcliente.setEnabled(false);
        txtfardos.setEnabled(false);
        txtpromo.setEnabled(false);
        txtentrego.setEnabled(false);
        txtdebe.setEnabled(false);
        txtcontacto.setEnabled(false);
        cmbestado.setEnabled(false);
        cmbrecibido.setEnabled(false);
        txtcomentarios.setEnabled(false);
        txtbuscar.setEnabled(false);
    }
    
    private void limpiar(){
        cmbempleado.setSelectedIndex(-1);
        cmbrecibido.setSelectedIndex(-1);
        cmbestado.setSelectedIndex(-1);
        txtcliente.setText("");
        txtfardos.setText("");
        txtpromo.setText("");
        txtentrego.setText("0.0");
        txtdebe.setText("0.0");
        txtcontacto.setText("");
        txtcomentarios.setText("");
        txtcodigo.setText("");
    }
    
    private void limpiar2(){
        cmbrecibido.setSelectedIndex(-1);
        cmbestado.setSelectedIndex(-1);
        txtcliente.setText("");
        txtfardos.setText("");
        txtpromo.setText("");
        txtentrego.setText("0.0");
        txtdebe.setText("0.0");
        txtcontacto.setText("");
        txtcomentarios.setText("");
    }
    
    public void CargarEmpleados() {
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT nom_emp FROM empleados ORDER BY nom_emp");
            cmbempleado.removeAllItems();
            while (rs.next()) {
                cmbempleado.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "ERROR: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void CargarAdmin() {
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT nom_admin FROM administradores ORDER BY nom_admin");
            cmbrecibido.removeAllItems();
            while (rs.next()) {
                cmbrecibido.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "ERROR: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void MostrarDatos(int dui){
        modelo= new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        modelo.addColumn("Código");
        modelo.addColumn("Fecha");
        modelo.addColumn("Cliente");
        modelo.addColumn("Fardos");
        modelo.addColumn("Promoción");
        modelo.addColumn("Entregó");
        modelo.addColumn("Deuda");
        modelo.addColumn("Contacto");
        modelo.addColumn("Estado");
        modelo.addColumn("Recibido por");
        modelo.addColumn("Comentarios");
        tablacre.setModel(modelo);
        String sql = "SELECT id_credito, fecha_credito, cliente_credito, cant_fardos_credito, promo_credito, cant_a_entr_cred, debe_cliente_credito, tel_cliente_credito, estado_credito, nom_admin, coment_credito FROM credito c INNER JOIN empleados e INNER JOIN administradores a ON c.id_emp=e.id_emp AND c.id_admin=a.id_admin WHERE e.id_emp = " + dui + " ORDER BY fecha_credito ASC";
        String []datos = new String [11];
        try {
            Statement st2 = cn.createStatement();
            ResultSet rs = st2.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                datos[9]=rs.getString(10);
                datos[10]=rs.getString(11);
                modelo.addRow(datos);
            }
            tablacre.setModel(modelo);
            tablacre.getTableHeader().setReorderingAllowed(false);
            TableColumnModel columnModel = tablacre.getColumnModel();
            for (int i = 0; i < columnModel.getColumnCount(); i++) {
                columnModel.getColumn(i).setPreferredWidth(120);
            }
        } catch (SQLException ex) {JOptionPane.showMessageDialog(this, "ERROR: " + ex, "Error", JOptionPane.ERROR_MESSAGE);}
    }
    
    private void BuscarCliente(String indicio, int dui){
        modelo= new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        modelo.addColumn("Código");
        modelo.addColumn("Fecha");
        modelo.addColumn("Cliente");
        modelo.addColumn("Fardos");
        modelo.addColumn("Promoción");
        modelo.addColumn("Entregó");
        modelo.addColumn("Deuda");
        modelo.addColumn("Contacto");
        modelo.addColumn("Estado");
        modelo.addColumn("Recibido por");
        modelo.addColumn("Comentarios");
        tablacre.setModel(modelo);
        String sql = "SELECT id_credito, fecha_credito, cliente_credito, cant_fardos_credito, promo_credito, cant_a_entr_cred, debe_cliente_credito, tel_cliente_credito, estado_credito, nom_admin, coment_credito FROM credito c INNER JOIN empleados e INNER JOIN administradores a ON c.id_emp=e.id_emp AND c.id_admin=a.id_admin WHERE cliente_credito LIKE '%" + indicio + "%' AND e.id_emp = " + dui + " OR estado_credito LIKE '%" + indicio + "%' AND e.id_emp = " + dui + " ORDER BY fecha_credito ASC";
        String []datos = new String [11];
        try {
            Statement st2 = cn.createStatement();
            ResultSet rs = st2.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                datos[9]=rs.getString(10);
                datos[10]=rs.getString(11);
                modelo.addRow(datos);
            }
            tablacre.setModel(modelo);
            tablacre.getTableHeader().setReorderingAllowed(false);
            TableColumnModel columnModel = tablacre.getColumnModel();
            for (int i = 0; i < columnModel.getColumnCount(); i++) {
                columnModel.getColumn(i).setPreferredWidth(120);
            }
        } catch (SQLException ex) {JOptionPane.showMessageDialog(this, "ERROR: " + ex, "Error", JOptionPane.ERROR_MESSAGE);}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCredito dialog = new frmCredito(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JComboBox<String> cmbempleado;
    private javax.swing.JComboBox<String> cmbestado;
    private org.freixas.jcalendar.JCalendarCombo cmbfecha;
    private javax.swing.JComboBox<String> cmbrecibido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private javax.swing.JTable tablacre;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextArea txtcomentarios;
    private javax.swing.JTextField txtcontacto;
    private javax.swing.JTextField txtdebe;
    private javax.swing.JTextField txtdui;
    private javax.swing.JTextField txtentrego;
    private javax.swing.JTextField txtfardos;
    private javax.swing.JTextField txtpromo;
    // End of variables declaration//GEN-END:variables
}
