/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Color;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.dropbox.core.*;
import java.awt.Desktop;
import java.io.*;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Calendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Will Vásquez
 */
public class frmDatabase extends javax.swing.JDialog {
    private Calendar calendar;

    /**
     * Creates new form frmDatabase
     */
    public frmDatabase(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Gestor de base de datos");
        getContentPane().setBackground(Color.DARK_GRAY);
        setResizable(false);
        FileFilter FiltroBackup = new FileNameExtensionFilter("Respaldo SQL","sql");
        FileRuta.setFileFilter(FiltroBackup);
        calendar = Calendar.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileRuta = new javax.swing.JFileChooser();
        btnrespaldo = new javax.swing.JButton();
        btnrespaldo1 = new javax.swing.JButton();
        btnrespaldo2 = new javax.swing.JButton();
        btnrespaldo3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnrespaldo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnrespaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/download_database.png"))); // NOI18N
        btnrespaldo.setText("Crear respaldo local");
        btnrespaldo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnrespaldo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnrespaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrespaldoActionPerformed(evt);
            }
        });

        btnrespaldo1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnrespaldo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/dropbox.png"))); // NOI18N
        btnrespaldo1.setText("Crear respaldo en DropBox");
        btnrespaldo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnrespaldo1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnrespaldo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrespaldo1ActionPerformed(evt);
            }
        });

        btnrespaldo2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnrespaldo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/upload_database.png"))); // NOI18N
        btnrespaldo2.setText("Restaurar DB");
        btnrespaldo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnrespaldo2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnrespaldo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrespaldo2ActionPerformed(evt);
            }
        });

        btnrespaldo3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnrespaldo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/delete_database.png"))); // NOI18N
        btnrespaldo3.setText("Eliminar todos los datos");
        btnrespaldo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnrespaldo3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnrespaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnrespaldo1)
                .addGap(18, 18, 18)
                .addComponent(btnrespaldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnrespaldo3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnrespaldo3)
                    .addComponent(btnrespaldo1)
                    .addComponent(btnrespaldo)
                    .addComponent(btnrespaldo2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrespaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrespaldoActionPerformed
        try {
            int ArchivoAbierto;
            ArchivoAbierto = FileRuta.showOpenDialog(this);
            if (ArchivoAbierto == JFileChooser.APPROVE_OPTION) {
                File ArchivoSeleccionado = new File(FileRuta.getSelectedFile().getCanonicalPath() + "." + ((FileNameExtensionFilter) FileRuta.getFileFilter()).getExtensions()[0]);
                String ruta = ArchivoSeleccionado.getAbsolutePath();
                Process p = Runtime.getRuntime().exec("C:/Program Files/MariaDB 10.1/bin/mysqldump --opt --user=root --password=19720716 ventas");
                InputStream is = p.getInputStream();
                try (FileOutputStream fos = new FileOutputStream(ruta)) {
                    byte[] buffer = new byte[1000];
                    int leido = is.read(buffer);
                    while (leido > 0) {
                        fos.write(buffer, 0, leido);
                        leido = is.read(buffer);
                    }     
                    JOptionPane.showMessageDialog(this, "Respaldo de base de datos creado con éxito");
                }
            }else {
                JOptionPane.showMessageDialog(this, "¡No se creó el backup de la base de datos!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (HeadlessException | IOException e) {JOptionPane.showMessageDialog(this, "Error: " + e, "ERROR", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_btnrespaldoActionPerformed

    private void btnrespaldo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrespaldo1ActionPerformed
        try {
            final String APP_KEY = "kjx0ph5uxexjfyy";
            final String APP_SECRET = "iw6eb4tx5u5eupq";
            DbxAppInfo appInfo = new DbxAppInfo(APP_KEY, APP_SECRET);
            DbxRequestConfig config = new DbxRequestConfig(
                "Respaldo_DropBox", Locale.getDefault().toString());
            DbxWebAuthNoRedirect webAuth = new DbxWebAuthNoRedirect(config, appInfo);
            String authorizeUrl = webAuth.start();
            Desktop.getDesktop().browse(new URI(authorizeUrl));
            String code = JOptionPane.showInputDialog(this,"Copie el código que se le proporcionó",JOptionPane.QUESTION_MESSAGE);
            DbxAuthFinish authFinish = webAuth.finish(code);
            String accessToken = authFinish.accessToken;
            DbxClient client = new DbxClient(config, accessToken);
            String ruta = "C:/Users/Will Vásquez/Documents/backup.sql";
            Process p = Runtime.getRuntime().exec("C:/Program Files/MariaDB 10.1/bin/mysqldump --opt --user=root --password=19720716 ventas");
            InputStream is = p.getInputStream();
            FileOutputStream fos = new FileOutputStream(ruta);
            byte[] buffer = new byte[1000];
            int leido = is.read(buffer);
            while (leido > 0) {fos.write(buffer, 0, leido);leido = is.read(buffer);} fos.close();
            int dia = calendar.get(Calendar.DAY_OF_MONTH);
            int mes = calendar.get(Calendar.MONTH)+1;
            int anio = calendar.get(Calendar.YEAR);
            File inputFile = new File(ruta);
            FileInputStream inputStream = new FileInputStream(inputFile);
            DbxEntry.File uploadedFile = client.uploadFile("/DbGlaciar/backup_"+dia+"_"+mes+"_"+anio+".sql", DbxWriteMode.add(), inputFile.length(), inputStream);
            inputStream.close();
            inputFile.delete();
            JOptionPane.showMessageDialog(this, "Se ha accedido a la cuenta de: " + client.getAccountInfo().displayName + "\nY se creó el siguiente respaldo: " + "backup"+dia+"_"+mes+"_"+anio+".sql");
        } catch (URISyntaxException | IOException | DbxException e) {JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);} 
    }//GEN-LAST:event_btnrespaldo1ActionPerformed

    private void btnrespaldo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrespaldo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrespaldo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmDatabase dialog = new frmDatabase(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileRuta;
    private javax.swing.JButton btnrespaldo;
    private javax.swing.JButton btnrespaldo1;
    private javax.swing.JButton btnrespaldo2;
    private javax.swing.JButton btnrespaldo3;
    // End of variables declaration//GEN-END:variables
}
