/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ClsConexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Will Vásquez
 */
public class frmGanacias extends javax.swing.JDialog {
    ClsConexion cc = new ClsConexion();
    Connection cn = cc.conectar();
    private PreparedStatement st;
    DefaultTableModel modelo;
    DecimalFormat df = new DecimalFormat("0.00");

    /**
     * Creates new form frmGanacias
     */
    public frmGanacias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Gestor de ganancias");
        getContentPane().setBackground(Color.DARK_GRAY);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcode = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbtipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbempleado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbdesde = new org.freixas.jcalendar.JCalendarCombo();
        jLabel4 = new javax.swing.JLabel();
        cmbhasta = new org.freixas.jcalendar.JCalendarCombo();
        jPanel2 = new javax.swing.JPanel();
        btncalcular = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        txtr1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        txtr2 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        txtr3 = new javax.swing.JLabel();
        txt4 = new javax.swing.JLabel();
        txtr4 = new javax.swing.JLabel();

        txtestado.setText("'Cancelado'");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sumatoria de:");

        cmbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ruta", "Mayoreo", "Crédito", "Frescos", "Frutsis" }));
        cmbtipo.setSelectedIndex(-1);
        cmbtipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbtipoItemStateChanged(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Empleado:");

        cmbempleado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbempleadoItemStateChanged(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Desde:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hasta:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbhasta, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(cmbdesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbtipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbempleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbdesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbhasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        btncalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/calculadora.png"))); // NOI18N
        btncalcular.setText("Calcular");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });

        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/limpiar.png"))); // NOI18N
        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/salir.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(btnlimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btncalcular)
                .addGap(18, 18, 18)
                .addComponent(btnlimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsalir)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        txt1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtr1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtr1.setForeground(new java.awt.Color(255, 255, 255));
        txtr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        txt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtr2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtr2.setForeground(new java.awt.Color(255, 255, 255));
        txtr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt3.setForeground(new java.awt.Color(255, 255, 255));
        txt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtr3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtr3.setForeground(new java.awt.Color(255, 255, 255));
        txtr3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt4.setForeground(new java.awt.Color(255, 255, 255));
        txt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtr4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtr4.setForeground(new java.awt.Color(255, 255, 255));
        txtr4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtr2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtr3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtr4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtr1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtr2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtr3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtr4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbtipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbtipoItemStateChanged
        switch (cmbtipo.getSelectedIndex()) {
            case 0:
                txt1.setText("Comisiones");
                txt2.setText("Sueldo");
                txt3.setText("Saldo Neto");
                txt4.setText("Fardos vendidos");
                break;
            case 1:
                txt1.setText("Comisiones");
                txt2.setText("Fardos a 0.75");
                txt3.setText("Fardos a 0.70");
                txt4.setText("Saldo Neto");
                break;
            case 2:
                txt1.setText("Total cancelado");
                txt2.setText("Fardos vendidos");
                txt3.setText("");
                txt4.setText("");
                break;
            case 3:
                txt1.setText("Comisiones");
                txt2.setText("Fardos vendidos");
                txt3.setText("Saldo Neto");
                txt4.setText("");
                break;
            case 4:
                txt1.setText("Comisiones");
                txt2.setText("Cajas vendidas");
                txt3.setText("Saldo Neto");
                txt4.setText("");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cmbtipoItemStateChanged

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        if(cmbtipo.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(this, "¡Debes seleccionar un tipo!", "Atención", JOptionPane.CANCEL_OPTION);
        }else if(cmbempleado.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(this, "¡Debes seleccionar un empleado!", "Atención", JOptionPane.CANCEL_OPTION);
        }else if(cmbdesde.getDate().compareTo(cmbhasta.getDate()) > 0 && !(cmbdesde.getSelectedItem().equals(cmbhasta.getSelectedItem()))){
            JOptionPane.showMessageDialog(this, "¡La fecha HASTA no puede ser menor que la fecha DESDE!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else{
            try {
                switch (cmbtipo.getSelectedIndex()) {
                    case 0:
                        {
                            st = cn.prepareStatement("SELECT SUM(ganancia_vend_ruta), SUM(sueldo_vend_ruta), SUM(saldo_neto_ruta), "
                                    + "SUM(vendidos_ruta) FROM rutas r INNER JOIN empleados e ON r.id_emp=e.id_emp WHERE "
                                    + "e.id_emp = ? AND fecha_ruta BETWEEN ? AND ?");
                            st.setInt(1, Integer.parseInt(txtcode.getText()));
                            java.sql.Date desde = new java.sql.Date(cmbdesde.getDate().getTime());
                            st.setDate(2, desde);
                            java.sql.Date hasta = new java.sql.Date(cmbhasta.getDate().getTime());
                            st.setDate(3, hasta);
                            ResultSet rs = st.executeQuery();
                            if(rs.next()){
                                String ganancia = rs.getString(1);
                                String sueldo = rs.getString(2);
                                String neto = rs.getString(3);
                                String vendidos = rs.getString(4);
                                txtr1.setText(String.valueOf(ganancia));
                                txtr2.setText(String.valueOf(sueldo));
                                txtr3.setText(String.valueOf(neto));
                                txtr4.setText(String.valueOf(vendidos));
                                if("null".equals(txtr1.getText()) || "null".equals(txtr2.getText()) || "null".equals(txtr3.getText()) || "null".equals(txtr4.getText())){
                                    txtr1.setText("0");
                                    txtr2.setText("0");
                                    txtr3.setText("0");
                                    txtr4.setText("0");
                                }
                            }       break;
                        }
                    case 1:
                        {
                            st = cn.prepareStatement("SELECT SUM(ganancia_vend_may), SUM(cant1_may), SUM(cant2_may), "
                                    + "SUM(saldo_neto_may) FROM mayoristas m INNER JOIN empleados e ON m.id_emp=e.id_emp WHERE "
                                    + "e.id_emp = ? AND fecha_mayoreo BETWEEN ? AND ?");
                            st.setInt(1, Integer.parseInt(txtcode.getText()));
                            java.sql.Date desde = new java.sql.Date(cmbdesde.getDate().getTime());
                            st.setDate(2, desde);
                            java.sql.Date hasta = new java.sql.Date(cmbhasta.getDate().getTime());
                            st.setDate(3, hasta);
                            ResultSet rs = st.executeQuery();
                            if(rs.next()){
                                String ganancia = rs.getString(1);
                                String sete = rs.getString(2);
                                String setecinco = rs.getString(3);
                                String neto = rs.getString(4);
                                txtr1.setText(String.valueOf(ganancia));
                                txtr2.setText(String.valueOf(sete));
                                txtr3.setText(String.valueOf(setecinco));
                                txtr4.setText(String.valueOf(neto));
                                if("null".equals(txtr1.getText()) || "null".equals(txtr2.getText()) || "null".equals(txtr3.getText()) || "null".equals(txtr4.getText())){
                                    txtr1.setText("0");
                                    txtr2.setText("0");
                                    txtr3.setText("0");
                                    txtr4.setText("0");
                                }
                            }       break;
                        }
                    case 2:
                        {
                            st = cn.prepareStatement("SELECT SUM(cant_a_entr_cred), SUM(cant_fardos_credito) "
                                    + "FROM credito c INNER JOIN empleados e ON c.id_emp=e.id_emp WHERE "
                                    + "e.id_emp = ? AND estado_credito = 'Cancelado' AND fecha_credito BETWEEN ? AND ?");
                            st.setInt(1, Integer.parseInt(txtcode.getText()));
                            java.sql.Date desde = new java.sql.Date(cmbdesde.getDate().getTime());
                            st.setDate(2, desde);
                            java.sql.Date hasta = new java.sql.Date(cmbhasta.getDate().getTime());
                            st.setDate(3, hasta);
                            ResultSet rs = st.executeQuery();
                            if(rs.next()){
                                String ganancia = rs.getString(1);
                                String vendidos = rs.getString(2);
                                txtr1.setText(String.valueOf(ganancia));
                                txtr2.setText(String.valueOf(vendidos));
                                if("null".equals(txtr1.getText()) || "null".equals(txtr2.getText())){
                                    txtr1.setText("0");
                                    txtr2.setText("0");
                                }
                            }       break;
                        }
                    case 3:
                        {
                            st = cn.prepareStatement("SELECT SUM(comision_refre), SUM(vendio_refre), SUM(neto_refre) "
                                    + "FROM refrescos r INNER JOIN empleados e ON r.id_emp=e.id_emp WHERE "
                                    + "e.id_emp = ? AND estado_refre = 'Cancelado' AND fecha_refre BETWEEN ? AND ?");
                            st.setInt(1, Integer.parseInt(txtcode.getText()));
                            java.sql.Date desde = new java.sql.Date(cmbdesde.getDate().getTime());
                            st.setDate(2, desde);
                            java.sql.Date hasta = new java.sql.Date(cmbhasta.getDate().getTime());
                            st.setDate(3, hasta);
                            ResultSet rs = st.executeQuery();
                            if(rs.next()){
                                String ganancia = rs.getString(1);
                                String vendidos = rs.getString(2);
                                String neto = rs.getString(3);
                                txtr1.setText(String.valueOf(ganancia));
                                txtr2.setText(String.valueOf(vendidos));
                                txtr3.setText(String.valueOf(neto));
                                if("null".equals(txtr1.getText()) || "null".equals(txtr2.getText()) || "null".equals(txtr3.getText())){
                                    txtr1.setText("0");
                                    txtr2.setText("0");
                                    txtr3.setText("0");
                                }
                            }       break;
                        }
                    case 4:
                        {
                            st = cn.prepareStatement("SELECT SUM(comision_frutsi), SUM(vendio_frutsi), SUM(neto_frutsi) "
                                    + "FROM frutsis f INNER JOIN empleados e ON f.id_emp=e.id_emp WHERE "
                                    + "e.id_emp = ? AND estado_frutsi = 'Cancelado' AND fecha_frutsi BETWEEN ? AND ?");
                            st.setInt(1, Integer.parseInt(txtcode.getText()));
                            java.sql.Date desde = new java.sql.Date(cmbdesde.getDate().getTime());
                            st.setDate(2, desde);
                            java.sql.Date hasta = new java.sql.Date(cmbhasta.getDate().getTime());
                            st.setDate(3, hasta);
                            ResultSet rs = st.executeQuery();
                            if(rs.next()){
                                String ganancia = rs.getString(1);
                                String vendidos = rs.getString(2);
                                String neto = rs.getString(3);
                                txtr1.setText(String.valueOf(ganancia));
                                txtr2.setText(String.valueOf(vendidos));
                                txtr3.setText(String.valueOf(neto));
                                if("null".equals(txtr1.getText()) || "null".equals(txtr2.getText()) || "null".equals(txtr3.getText())){
                                    txtr1.setText("0");
                                    txtr2.setText("0");
                                    txtr3.setText("0");
                                }
                            }       break;
                        }
                    default:
                        break;
                }
            } catch (SQLException | NumberFormatException e) {JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_btncalcularActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CargarEmpleados();
        cmbempleado.setSelectedIndex(-1);
    }//GEN-LAST:event_formWindowOpened

    private void cmbempleadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbempleadoItemStateChanged
        if(cmbempleado.getSelectedIndex() > -1){
            txtr1.setText("");
            txtr2.setText("");
            txtr3.setText("");
            txtr4.setText("");
            try {
                st = cn.prepareStatement("SELECT id_emp FROM empleados WHERE nom_emp = ?");
                st.setString(1, cmbempleado.getSelectedItem().toString());
                ResultSet rs2 = st.executeQuery();
                rs2.next();
                int admin2 = rs2.getInt(1);
                txtcode.setText(String.valueOf(admin2));
            } catch (Exception e) { 
                JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cmbempleadoItemStateChanged

    public void CargarEmpleados() {
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT nom_emp FROM empleados ORDER BY nom_emp");
            cmbempleado.removeAllItems();
            while (rs.next()) {
                cmbempleado.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "ERROR: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void limpiar(){
        cmbempleado.setSelectedIndex(-1);
        cmbtipo.setSelectedIndex(-1);
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
        txt4.setText("");
        txtr1.setText("");
        txtr2.setText("");
        txtr3.setText("");
        txtr4.setText("");
    }
    
    public void limpiar2(){
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
        txt4.setText("");
        txtr1.setText("");
        txtr2.setText("");
        txtr3.setText("");
        txtr4.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGanacias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGanacias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGanacias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGanacias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmGanacias dialog = new frmGanacias(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnsalir;
    private org.freixas.jcalendar.JCalendarCombo cmbdesde;
    private javax.swing.JComboBox<String> cmbempleado;
    private org.freixas.jcalendar.JCalendarCombo cmbhasta;
    private javax.swing.JComboBox<String> cmbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtestado;
    private javax.swing.JLabel txtr1;
    private javax.swing.JLabel txtr2;
    private javax.swing.JLabel txtr3;
    private javax.swing.JLabel txtr4;
    // End of variables declaration//GEN-END:variables
}
