/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ClsConexion;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Will Vásquez
 */
public class frmRutaRefrescos_1 extends javax.swing.JDialog {
    ClsConexion cc = new ClsConexion();
    Connection cn = cc.conectar();
    private PreparedStatement st;
    DefaultTableModel modelo;
    DecimalFormat df = new DecimalFormat("0.00");

    /**
     * Creates new form frmRutaRefrescos
     */
    public frmRutaRefrescos_1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Gestor venta de refrescos");
        getContentPane().setBackground(Color.DARK_GRAY);
        setResizable(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcodigo = new javax.swing.JTextField();
        txtcode = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbempleados = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbfecha = new org.freixas.jcalendar.JCalendarCombo();
        jLabel3 = new javax.swing.JLabel();
        txtsalida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdevueltos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtentregado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbrecibido = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbtipo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblvendidos = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblesperada = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblcomision = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblnetos = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcomentarios = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        txtdebe = new javax.swing.JTextField();
        cmbestado = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        lblestado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablarefre = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Empleado:");

        cmbempleados.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbempleadosItemStateChanged(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad salida:");

        txtsalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsalidaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsalidaKeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad devueltos:");

        txtdevueltos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdevueltosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdevueltosKeyTyped(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Entregado ($):");

        txtentregado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtentregadoFocusLost(evt);
            }
        });
        txtentregado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtentregadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtentregadoKeyTyped(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Recibido por:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo:");

        cmbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contado", "Credito " }));
        cmbtipo.setSelectedIndex(-1);
        cmbtipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbtipoItemStateChanged(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cliente:");

        txtcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtclienteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsalida)
                            .addComponent(txtdevueltos, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(txtentregado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbrecibido, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbempleados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(cmbtipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcliente))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbempleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtsalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdevueltos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtentregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbrecibido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Cálculos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fardos vendidos:");

        lblvendidos.setForeground(new java.awt.Color(255, 255, 255));
        lblvendidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cantidad esperada ($):");

        lblesperada.setForeground(new java.awt.Color(255, 255, 255));
        lblesperada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Estado:");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Comisión ($):");

        lblcomision.setForeground(new java.awt.Color(255, 255, 255));
        lblcomision.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Saldo neto ($):");

        lblnetos.setForeground(new java.awt.Color(255, 255, 255));
        lblnetos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Comentarios:");

        txtcomentarios.setColumns(20);
        txtcomentarios.setLineWrap(true);
        txtcomentarios.setRows(2);
        txtcomentarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcomentariosKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtcomentarios);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Debe:");

        txtdebe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdebe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdebeFocusLost(evt);
            }
        });
        txtdebe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdebeKeyTyped(evt);
            }
        });

        cmbestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Cancelado" }));
        cmbestado.setSelectedIndex(-1);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Estado credito:");

        lblestado.setForeground(new java.awt.Color(255, 255, 255));
        lblestado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblvendidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblesperada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtdebe)
                            .addComponent(cmbestado, 0, 171, Short.MAX_VALUE)
                            .addComponent(lblestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblnetos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblcomision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblvendidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblesperada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtdebe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblcomision, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblnetos, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/agregar.png"))); // NOI18N
        btnguardar.setText("Guardar datos");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/edit.png"))); // NOI18N
        btnmodificar.setText("Modificar datos");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btnconsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/consultar.png"))); // NOI18N
        btnconsultar.setText("Consultar datos");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/eliminar.png"))); // NOI18N
        btneliminar.setText("Eliminar datos");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/limpiar.png"))); // NOI18N
        btnlimpiar.setText("Limpiar datos");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnconsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnguardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmodificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnconsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btneliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablarefre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablarefre.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablarefre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablarefreMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablarefre);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CargarEmpleados();
        CargarAdmin();
        bloquear();
        cmbempleados.setSelectedIndex(-1);
        cmbrecibido.setSelectedIndex(-1);
    }//GEN-LAST:event_formWindowOpened

    private void cmbempleadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbempleadosItemStateChanged
        if(cmbempleados.getSelectedIndex() > -1){
            cmbrecibido.setEnabled(true);
            cmbfecha.setEnabled(true);
            txtsalida.setEnabled(true);
            txtdevueltos.setEnabled(true);
            txtentregado.setEnabled(true);
            txtcomentarios.setEnabled(true);
            limpiar2();
            tablarefre.setModel(new DefaultTableModel());
            try {
                st = cn.prepareStatement("SELECT id_emp FROM empleados WHERE nom_emp = ?");
                st.setString(1, cmbempleados.getSelectedItem().toString());
                ResultSet rs2 = st.executeQuery();
                rs2.next();
                int admin2 = rs2.getInt(1);
                txtcode.setText(String.valueOf(admin2));
            } catch (Exception e) { 
                JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cmbempleadosItemStateChanged

    private void txtsalidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsalidaKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || txtsalida.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_txtsalidaKeyTyped

    private void txtdevueltosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdevueltosKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || txtdevueltos.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_txtdevueltosKeyTyped

    private void txtentregadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtentregadoKeyTyped
        try {
            if (!Character.isDigit(evt.getKeyChar()) && !(evt.getKeyChar() == '.') || txtentregado.getText().length() >= 7) {
                evt.consume();
            }
            Double.parseDouble(txtentregado.getText() + evt.getKeyChar());
        } catch (NumberFormatException e) {
            evt.consume();
        }
    }//GEN-LAST:event_txtentregadoKeyTyped

    private void txtentregadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtentregadoFocusLost
        if (txtentregado.getText().isEmpty()) {
        } else {
            String precio = df.format(Double.parseDouble(txtentregado.getText()));
            precio = precio.replaceAll(",", ".");
            try {
                txtentregado.setText(precio);
            } catch (NumberFormatException e) {
                txtentregado.setText(null);
            }
        }
    }//GEN-LAST:event_txtentregadoFocusLost

    private void txtsalidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsalidaKeyReleased
        if ("".equals(txtsalida.getText()) || "".equals(txtdevueltos.getText())) {
            lblvendidos.setText("0");
            lblesperada.setText("0");
        }else{
            int vendidos = Integer.parseInt(txtsalida.getText()) - Integer.parseInt(txtdevueltos.getText());
            lblvendidos.setText(String.valueOf(vendidos));
            double esperado = Integer.parseInt(lblvendidos.getText()) * 1.75;
            lblesperada.setText(String.valueOf(df.format(esperado)));
            double comision = Integer.parseInt(lblvendidos.getText()) * 0.25;
            lblcomision.setText(String.valueOf(df.format(comision)));
            lblnetos.setText(String.valueOf(df.format(comision)));
        }
    }//GEN-LAST:event_txtsalidaKeyReleased

    private void txtdevueltosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdevueltosKeyReleased
        if ("".equals(txtsalida.getText()) || "".equals(txtdevueltos.getText())) {
            lblvendidos.setText("0");
            lblesperada.setText("0");
        }else{
            int vendidos = Integer.parseInt(txtsalida.getText()) - Integer.parseInt(txtdevueltos.getText());
            lblvendidos.setText(String.valueOf(vendidos));
            double esperado = Integer.parseInt(lblvendidos.getText()) * 1.75;
            lblesperada.setText(String.valueOf(df.format(esperado)));
            double comision = Integer.parseInt(lblvendidos.getText()) * 0.25;
            lblcomision.setText(String.valueOf(df.format(comision)));
            lblnetos.setText(String.valueOf(df.format(comision)));
        }
    }//GEN-LAST:event_txtdevueltosKeyReleased

    private void txtentregadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtentregadoKeyReleased
        if ("".equals(txtentregado.getText())) {
            lblestado.setText("");
        }else if (Double.parseDouble(txtentregado.getText()) >= Double.parseDouble(lblesperada.getText())){
            lblestado.setText("Todo en orden");
        }else{
            lblestado.setText("Error");
        }
    }//GEN-LAST:event_txtentregadoKeyReleased

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        bloquear();
        limpiar();
        tablarefre.setModel(new DefaultTableModel());
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        if (cmbempleados.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un empleado para realizar la consulta", "AVISO", JOptionPane.CANCEL_OPTION);
        } else {
            MostrarDatos(Integer.parseInt(txtcode.getText()));
        }
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if (cmbempleados.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "¡Debes seleccionar un empleado!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if(txtsalida.getText().isEmpty() || txtdevueltos.getText().isEmpty() || txtentregado.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "¡No puedes dejar campos en blanco!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if (cmbrecibido.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "¿Quién ha recibido la venta?", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if (cmbtipo.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "¡Debes seleccionar el tipo de venta!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else{
            try {
                st = cn.prepareStatement("SELECT id_emp FROM empleados WHERE nom_emp = ?");
                st.setString(1, cmbempleados.getSelectedItem().toString());
                ResultSet rs = st.executeQuery();
                if (rs.next()) {
                    String empleado = rs.getString(1);
                    st = cn.prepareStatement("SELECT id_admin FROM administradores WHERE nom_admin = ?");
                    st.setString(1, cmbrecibido.getSelectedItem().toString());
                    ResultSet rs2 = st.executeQuery();
                    if (rs2.next()) {
                        String admin = rs2.getString(1);
                        if(cmbtipo.getSelectedIndex() == 0){
                            st = cn.prepareStatement("INSERT INTO refrescos(fecha_refre, tipo_ventar, cliente_refre, salida_refre, devueltos_refre, vendio_refre, "
                                    + "entrego_refre, esperaba_refre, debe_refre, estado_refre, comision_refre, neto_refre, coment_refre, id_emp, id_admin) "
                                    + "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                            java.sql.Date sqlFecha = new java.sql.Date(cmbfecha.getDate().getTime());
                            st.setDate(1, sqlFecha);
                            st.setString(2, cmbtipo.getSelectedItem().toString());
                            st.setString(3, "No especificado.");
                            st.setInt(4, Integer.parseInt(txtsalida.getText()));
                            st.setInt(5, Integer.parseInt(txtdevueltos.getText()));
                            st.setInt(6, Integer.parseInt(lblvendidos.getText()));
                            st.setDouble(7, Double.parseDouble(txtentregado.getText()));
                            st.setDouble(8, Double.parseDouble(lblesperada.getText()));
                            st.setDouble(9, Double.parseDouble(txtdebe.getText()));
                            st.setString(10, "Cancelado");
                            st.setDouble(11, Double.parseDouble(lblcomision.getText()));
                            st.setDouble(12, Double.parseDouble(lblnetos.getText()));
                            if(txtcomentarios.getText().isEmpty()){
                                st.setString(13, "No hay comentarios.");
                            }else{st.setString(13, txtcomentarios.getText());}
                            st.setInt(14, Integer.parseInt(empleado));
                            st.setInt(15, Integer.parseInt(admin));
                            st.executeUpdate();
                            JOptionPane.showMessageDialog(rootPane, "Datos guardados con éxito");
                            bloquear();
                            limpiar();
                            tablarefre.setModel(new DefaultTableModel());
                        }else if(cmbtipo.getSelectedIndex() == 1){
                            if(cmbestado.getSelectedIndex() < 0){
                                JOptionPane.showMessageDialog(this, "¡Debes seleccionar un estado!", "AVISO", JOptionPane.CANCEL_OPTION);
                            }else if(txtcliente.getText().isEmpty()){
                                JOptionPane.showMessageDialog(this, "¡Debes especificar el cliente!", "AVISO", JOptionPane.CANCEL_OPTION);
                            }else{
                                st = cn.prepareStatement("INSERT INTO refrescos(fecha_refre, tipo_ventar, cliente_refre, salida_refre, devueltos_refre, vendio_refre, "
                                        + "entrego_refre, esperaba_refre, debe_refre, estado_refre, comision_refre, neto_refre, coment_refre, id_emp, id_admin) "
                                        + "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                                java.sql.Date sqlFecha = new java.sql.Date(cmbfecha.getDate().getTime());
                                st.setDate(1, sqlFecha);
                                st.setString(2, cmbtipo.getSelectedItem().toString());
                                st.setString(3, txtcliente.getText());
                                st.setInt(4, Integer.parseInt(txtsalida.getText()));
                                st.setInt(5, Integer.parseInt(txtdevueltos.getText()));
                                st.setInt(6, Integer.parseInt(lblvendidos.getText()));
                                st.setDouble(7, Double.parseDouble(txtentregado.getText()));
                                st.setDouble(8, Double.parseDouble(lblesperada.getText()));
                                st.setDouble(9, Double.parseDouble(txtdebe.getText()));
                                st.setString(10, cmbestado.getSelectedItem().toString());
                                st.setDouble(11, Double.parseDouble(lblcomision.getText()));
                                st.setDouble(12, Double.parseDouble(lblnetos.getText()));
                                if(txtcomentarios.getText().isEmpty()){
                                    st.setString(13, "No hay comentarios.");
                                }else{st.setString(13, txtcomentarios.getText());}
                                st.setInt(14, Integer.parseInt(empleado));
                                st.setInt(15, Integer.parseInt(admin));
                                st.executeUpdate();
                                JOptionPane.showMessageDialog(rootPane, "Datos guardados con éxito");
                                bloquear();
                                limpiar();
                                tablarefre.setModel(new DefaultTableModel());
                            }
                        }
                    }
                }
            } catch (SQLException | NumberFormatException e) {JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        if("".equals(txtcodigo.getText())){
            JOptionPane.showMessageDialog(this, "¡Debes realizar una consulta y seleccionarla!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if(cmbempleados.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(this, "¡Debes seleccionar un empleado!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if(txtsalida.getText().isEmpty() || txtdevueltos.getText().isEmpty() || txtentregado.getText().isEmpty() || txtcliente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "¡No puedes dejar campos en blanco!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if (cmbrecibido.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "¿Quién ha recibido la venta?", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if (cmbtipo.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "¡Debes seleccionar el tipo de venta!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if (cmbestado.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "¡Debes seleccionar el estado!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else{
            try {
                st = cn.prepareStatement("SELECT id_emp FROM empleados WHERE nom_emp = ?");
                st.setString(1, cmbempleados.getSelectedItem().toString());
                ResultSet rs = st.executeQuery();
                if (rs.next()) {
                    String empleado = rs.getString(1);
                    st = cn.prepareStatement("SELECT id_admin FROM administradores WHERE nom_admin = ?");
                    st.setString(1, cmbrecibido.getSelectedItem().toString());
                    ResultSet rs2 = st.executeQuery();
                    if (rs2.next()) {
                        String admin = rs2.getString(1);
                        st = cn.prepareStatement("UPDATE refrescos SET fecha_refre = ?, tipo_ventar = ?, cliente_refre = ?, salida_refre = ?, devueltos_refre = ?, vendio_refre = ?, "
                                + "entrego_refre = ?, esperaba_refre = ?, debe_refre = ?, estado_refre = ?, comision_refre = ?, neto_refre = ?, coment_refre = ?, id_emp = ?, id_admin = ? "
                                + "WHERE id_refre = ?");
                        java.sql.Date sqlFecha = new java.sql.Date(cmbfecha.getDate().getTime());
                        st.setDate(1, sqlFecha);
                        st.setString(2, cmbtipo.getSelectedItem().toString());
                        st.setString(3, txtcliente.getText());
                        st.setInt(4, Integer.parseInt(txtsalida.getText()));
                        st.setInt(5, Integer.parseInt(txtdevueltos.getText()));
                        st.setInt(6, Integer.parseInt(lblvendidos.getText()));
                        st.setDouble(7, Double.parseDouble(txtentregado.getText()));
                        st.setDouble(8, Double.parseDouble(lblesperada.getText()));
                        st.setDouble(9, Double.parseDouble(txtdebe.getText()));
                        st.setString(10, cmbestado.getSelectedItem().toString());
                        st.setDouble(11, Double.parseDouble(lblcomision.getText()));
                        st.setDouble(12, Double.parseDouble(lblnetos.getText()));
                        if(txtcomentarios.getText().isEmpty()){
                            st.setString(13, "No hay comentarios.");
                        }else{st.setString(13, txtcomentarios.getText());}
                        st.setInt(14, Integer.parseInt(empleado));
                        st.setInt(15, Integer.parseInt(admin));
                        st.setInt(16, Integer.parseInt(txtcodigo.getText()));
                        st.executeUpdate();
                        JOptionPane.showMessageDialog(rootPane, "Datos modificados con éxito");
                        MostrarDatos(Integer.parseInt(txtcode.getText()));
                        limpiar2();
                    }
                }
            } catch (SQLException | NumberFormatException e) {Logger.getLogger(frmRutaRefrescos_1.class.getName()).log(Level.SEVERE, null, e);}
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if("".equals(txtcodigo.getText())){
            JOptionPane.showMessageDialog(this, "¡Debes realizar y seleccionar una consulta para eliminar!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else{
            try {
                st = cn.prepareStatement("DELETE FROM refrescos WHERE id_refre = ?");
                st.setInt(1, Integer.parseInt(txtcodigo.getText()));
                if(JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro que desea eliminar estos datos?" + "\n¡Ya no podrán ser recuperados!", "Confirmación", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "Datos eliminados con éxito");
                    MostrarDatos(Integer.parseInt(txtcode.getText()));
                    bloquear();
                    limpiar();
                    cmbempleados.setSelectedIndex(-1);
                    tablarefre.setModel(new DefaultTableModel());
                }
            } catch (SQLException | NumberFormatException | HeadlessException e) {JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtcomentariosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcomentariosKeyTyped
        if (txtcomentarios.getText().length() >= 195) {
            evt.consume();
        }
    }//GEN-LAST:event_txtcomentariosKeyTyped

    private void cmbtipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbtipoItemStateChanged
        if(cmbtipo.getSelectedIndex() == 0){
            block();
        }else if(cmbtipo.getSelectedIndex() == 1){
            desblock();
        }
    }//GEN-LAST:event_cmbtipoItemStateChanged

    private void txtdebeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdebeKeyTyped
        try {
            if (!Character.isDigit(evt.getKeyChar()) && !(evt.getKeyChar() == '.') || txtdebe.getText().length() >= 5) {
                evt.consume();
            }
            Double.parseDouble(txtdebe.getText() + evt.getKeyChar());
        } catch (NumberFormatException e) {
            evt.consume();
        }
    }//GEN-LAST:event_txtdebeKeyTyped

    private void txtdebeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdebeFocusLost
        if (txtdebe.getText().isEmpty()) {
            txtdebe.setText("0.0");
        } else {
            String precio = df.format(Double.parseDouble(txtdebe.getText()));
            precio = precio.replaceAll(",", ".");
            try {
                txtdebe.setText(precio);
            } catch (NumberFormatException e) {
                txtdebe.setText(null);
            }
        }
    }//GEN-LAST:event_txtdebeFocusLost

    private void txtclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclienteKeyTyped
        if (txtsalida.getText().length() >= 75) {
            evt.consume();
        }
    }//GEN-LAST:event_txtclienteKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(null, "ATENCIÓN" + "\nLe recomendamos que verifique si ha ingresado correctamente los datos de este día" + "\nDicho esto, ¿Desea cerrar la ventana?", "AVISO", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
        }else{
            dispose();
            frmRutaRefrescos_1 obj = new frmRutaRefrescos_1(null, true);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void tablarefreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablarefreMouseClicked
        try {
            txtcodigo.setText(tablarefre.getValueAt(tablarefre.getSelectedRow(), 0).toString());
            SimpleDateFormat Formateador = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date fecha = Formateador.parse(tablarefre.getValueAt(tablarefre.getSelectedRow(), 1).toString());
            cmbfecha.setSelectedIndex(-1);
            cmbfecha.setDate(fecha);
            cmbtipo.setSelectedItem(tablarefre.getValueAt(tablarefre.getSelectedRow(), 2).toString());
            txtcliente.setText(tablarefre.getValueAt(tablarefre.getSelectedRow(), 3).toString());
            txtsalida.setText(tablarefre.getValueAt(tablarefre.getSelectedRow(), 4).toString());
            txtdevueltos.setText(tablarefre.getValueAt(tablarefre.getSelectedRow(), 5).toString());
            txtentregado.setText(tablarefre.getValueAt(tablarefre.getSelectedRow(), 6).toString());
            lblvendidos.setText(tablarefre.getValueAt(tablarefre.getSelectedRow(), 7).toString());
            lblesperada.setText(tablarefre.getValueAt(tablarefre.getSelectedRow(), 8).toString());
            txtdebe.setText(tablarefre.getValueAt(tablarefre.getSelectedRow(), 9).toString());
            cmbestado.setSelectedItem(tablarefre.getValueAt(tablarefre.getSelectedRow(), 10).toString());
            lblcomision.setText(tablarefre.getValueAt(tablarefre.getSelectedRow(), 11).toString());
            lblnetos.setText(tablarefre.getValueAt(tablarefre.getSelectedRow(), 12).toString());
            cmbrecibido.setSelectedItem(tablarefre.getValueAt(tablarefre.getSelectedRow(), 13).toString());
            txtcomentarios.setText(tablarefre.getValueAt(tablarefre.getSelectedRow(), 14).toString());
        } catch (Exception e) {JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_tablarefreMouseClicked

    public void CargarEmpleados() {
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT nom_emp FROM empleados ORDER BY nom_emp");
            cmbempleados.removeAllItems();
            while (rs.next()) {
                cmbempleados.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "ERROR: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void CargarAdmin() {
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT nom_admin FROM administradores ORDER BY nom_admin");
            cmbrecibido.removeAllItems();
            while (rs.next()) {
                cmbrecibido.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "ERROR: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void MostrarDatos(int code){
        modelo= new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        modelo.addColumn("Código");
        modelo.addColumn("Fecha");
        modelo.addColumn("Tipo venta");
        modelo.addColumn("Cliente");
        modelo.addColumn("Salida");
        modelo.addColumn("Devueltos");
        modelo.addColumn("Entregó");
        modelo.addColumn("Vendió");
        modelo.addColumn("Se esperaba");
        modelo.addColumn("Debe");
        modelo.addColumn("Estado");
        modelo.addColumn("Comisión");
        modelo.addColumn("Saldo neto");
        modelo.addColumn("Recibido por");
        modelo.addColumn("Comentarios");
        tablarefre.setModel(modelo);
        String sql = "SELECT id_refre, DATE_FORMAT(fecha_refre, '%d/%m/%Y') AS formatted_date, tipo_ventar, cliente_refre, salida_refre, devueltos_refre, entrego_refre, vendio_refre, esperaba_refre, debe_refre, estado_refre, comision_refre, neto_refre, nom_admin, coment_refre FROM refrescos r INNER JOIN empleados e INNER JOIN administradores a ON r.id_emp=e.id_emp AND r.id_admin=a.id_admin WHERE e.id_emp =" + code + " ORDER BY fecha_refre ASC";
        String []datos = new String [15];
        try {
            Statement st2 = cn.createStatement();
            ResultSet rs = st2.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                datos[9]=rs.getString(10);
                datos[10]=rs.getString(11);
                datos[11]=rs.getString(12);
                datos[12]=rs.getString(13);
                datos[13]=rs.getString(14);
                datos[14]=rs.getString(15);
                modelo.addRow(datos);
            }
            tablarefre.setModel(modelo);
            tablarefre.getTableHeader().setReorderingAllowed(false) ;
            TableColumnModel columnModel = tablarefre.getColumnModel();
            for (int i = 0; i < columnModel.getColumnCount(); i++) {
                columnModel.getColumn(i).setPreferredWidth(120);
            }
        } catch (SQLException ex) {JOptionPane.showMessageDialog(rootPane, "ERROR: " + ex, "ERROR", JOptionPane.ERROR_MESSAGE);}
    }
    
    public void limpiar(){
        cmbempleados.setSelectedIndex(-1);
        cmbrecibido.setSelectedIndex(-1);
        cmbtipo.setSelectedIndex(-1);
        cmbestado.setSelectedIndex(-1);
        txtcliente.setText("");
        txtsalida.setText("");
        txtdevueltos.setText("");
        cmbestado.setSelectedIndex(-1);
        txtentregado.setText("");
        txtcomentarios.setText("");
        txtcodigo.setText("");
        lblvendidos.setText("0");
        lblesperada.setText("0");
        lblnetos.setText("0");
        lblcomision.setText("0");
        lblestado.setText("");
        txtdebe.setText("0.0");
    }
    
    public void limpiar2(){
        cmbrecibido.setSelectedIndex(-1);
        txtsalida.setText("");
        lblestado.setText("");
        txtdevueltos.setText("");
        cmbestado.setSelectedIndex(-1);
        txtentregado.setText("");
        txtcomentarios.setText("");
        txtcodigo.setText("");
        lblvendidos.setText("0");
        lblesperada.setText("0");
        lblnetos.setText("0");
        lblcomision.setText("0");
        txtdebe.setText("0.0");
        cmbtipo.setSelectedIndex(-1);
        cmbestado.setSelectedIndex(-1);
        txtcliente.setText("");
    }
    
    public void bloquear(){
        cmbrecibido.setEnabled(false);
        cmbfecha.setEnabled(false);
        txtsalida.setEnabled(false);
        txtdevueltos.setEnabled(false);
        txtentregado.setEnabled(false);
        txtcomentarios.setEnabled(false);
        txtcliente.setEnabled(false);
        cmbestado.setEnabled(false);
        txtdebe.setEnabled(false);
        txtdebe.setText("0.0");
    }
    
    public void block(){
        txtcliente.setEnabled(false);
        cmbestado.setEnabled(false);
        txtdebe.setEnabled(false);
        txtdebe.setText("0.0");
    }
    
    public void desblock(){
        txtcliente.setEnabled(true);
        cmbestado.setEnabled(true);
        txtdebe.setEnabled(true);
        txtdebe.setText("0.0");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRutaRefrescos_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRutaRefrescos_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRutaRefrescos_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRutaRefrescos_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmRutaRefrescos_1 dialog = new frmRutaRefrescos_1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JComboBox<String> cmbempleados;
    private javax.swing.JComboBox<String> cmbestado;
    private org.freixas.jcalendar.JCalendarCombo cmbfecha;
    private javax.swing.JComboBox<String> cmbrecibido;
    private javax.swing.JComboBox<String> cmbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblcomision;
    private javax.swing.JLabel lblesperada;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblnetos;
    private javax.swing.JLabel lblvendidos;
    private javax.swing.JTable tablarefre;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextArea txtcomentarios;
    private javax.swing.JTextField txtdebe;
    private javax.swing.JTextField txtdevueltos;
    private javax.swing.JTextField txtentregado;
    private javax.swing.JTextField txtsalida;
    // End of variables declaration//GEN-END:variables
}
