/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ClsConexion;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Hashtable;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Will Vásquez
 */
public class frmRuta extends javax.swing.JDialog {
    ClsConexion cc = new ClsConexion();
    Connection cn = cc.conectar();
    private PreparedStatement st;
    DefaultTableModel modelo;
    DecimalFormatSymbols simbolos = DecimalFormatSymbols.getInstance(Locale.ENGLISH);
    DecimalFormat df = new DecimalFormat("0.00", simbolos);
    
    Hashtable<String, String> admins = new Hashtable<String, String>();

    /**
     * Creates new form frmRuta
     */
    public frmRuta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Gestor de rutas");
        getContentPane().setBackground(Color.DARK_GRAY);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtempleado = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbempleados = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbfecha = new org.freixas.jcalendar.JCalendarCombo();
        jLabel3 = new javax.swing.JLabel();
        txtsalida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtdevueltos = new javax.swing.JTextField();
        cmbrecibido = new javax.swing.JComboBox<>();
        txtentregado = new javax.swing.JTextField();
        txtgas = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblcomision = new javax.swing.JLabel();
        lblneto = new javax.swing.JLabel();
        lblestado = new javax.swing.JLabel();
        lblesperada = new javax.swing.JLabel();
        lblvendidos = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcomentarios = new javax.swing.JTextArea();
        lblsueldo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaruta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Empleado:");

        cmbempleados.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbempleadosItemStateChanged(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad de salida:");

        txtsalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsalidaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsalidaKeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad devueltos:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dinero entregado ($):");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gasolina ($):");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Recibido por:");

        txtdevueltos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdevueltosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdevueltosKeyTyped(evt);
            }
        });

        txtentregado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtentregadoFocusLost(evt);
            }
        });
        txtentregado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtentregadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtentregadoKeyTyped(evt);
            }
        });

        txtgas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgasKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsalida)
                            .addComponent(cmbfecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(cmbempleados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtgas)
                            .addComponent(cmbrecibido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtentregado)
                            .addComponent(txtdevueltos))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbempleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtsalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdevueltos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtentregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtgas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbrecibido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Cálculos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fardos vendidos:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cantidad esperada ($):");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Estado:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Comisión vendedor ($):");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Sueldo vendedor ($):");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Saldo neto ($):");

        lblcomision.setForeground(new java.awt.Color(255, 255, 255));
        lblcomision.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblneto.setForeground(new java.awt.Color(255, 255, 255));
        lblneto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblestado.setForeground(new java.awt.Color(255, 255, 255));
        lblestado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblesperada.setForeground(new java.awt.Color(255, 255, 255));
        lblesperada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblvendidos.setForeground(new java.awt.Color(255, 255, 255));
        lblvendidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Comentarios (?):");

        jScrollPane1.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N

        txtcomentarios.setColumns(20);
        txtcomentarios.setLineWrap(true);
        txtcomentarios.setRows(2);
        txtcomentarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcomentariosKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtcomentarios);

        lblsueldo.setForeground(new java.awt.Color(255, 255, 255));
        lblsueldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcomision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblneto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblesperada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblvendidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(lblsueldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblvendidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblesperada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblcomision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblsueldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblneto, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel20)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/agregar.png"))); // NOI18N
        btnguardar.setText("Guardar datos");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/edit.png"))); // NOI18N
        btnmodificar.setText("Modificar datos");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btnconsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/consultar.png"))); // NOI18N
        btnconsultar.setText("Consultar datos");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/eliminar.png"))); // NOI18N
        btneliminar.setText("Eliminar datos");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/limpiar.png"))); // NOI18N
        btnlimpiar.setText("Limpiar campos");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnconsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnguardar)
                .addGap(18, 18, 18)
                .addComponent(btnmodificar)
                .addGap(18, 18, 18)
                .addComponent(btnconsultar)
                .addGap(18, 18, 18)
                .addComponent(btneliminar)
                .addGap(18, 18, 18)
                .addComponent(btnlimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaruta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaruta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaruta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablarutaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaruta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CargarEmpleados();
        cmbempleados.setSelectedIndex(-1);
        CargarAdmin();
        cmbrecibido.setSelectedIndex(-1);
        bloquear();
    }//GEN-LAST:event_formWindowOpened

    private void cmbempleadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbempleadosItemStateChanged
        if (cmbempleados.getSelectedIndex() > -1) {
            cmbfecha.setEnabled(true);
            cmbrecibido.setEnabled(true);
            txtsalida.setEnabled(true);
            txtdevueltos.setEnabled(true);
            txtentregado.setEnabled(true);
            txtgas.setEnabled(true);
            tablaruta.setModel(new DefaultTableModel());
            limpiar2();
            try {
                st = cn.prepareStatement("SELECT id_emp FROM empleados WHERE nom_emp = ?");
                st.setString(1, cmbempleados.getSelectedItem().toString());
                ResultSet rs2 = st.executeQuery();
                rs2.next();
                int admin = rs2.getInt(1);
                txtempleado.setText(String.valueOf(admin));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cmbempleadosItemStateChanged

    private void txtsalidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsalidaKeyReleased
        if ("".equals(txtsalida.getText()) || "".equals(txtdevueltos.getText())) {
            lblvendidos.setText("0");
            lblesperada.setText("0");
            lblsueldo.setText("0");
        } else {
            int vendidos = Integer.parseInt(txtsalida.getText()) - Integer.parseInt(txtdevueltos.getText());
            lblvendidos.setText(String.valueOf(vendidos));
            double esperado = Integer.parseInt(lblvendidos.getText()) * 0.83;
            lblesperada.setText(String.valueOf(df.format(esperado)));
            if(vendidos > 115){
                double sueldo = vendidos * 0.08;
                lblsueldo.setText(String.valueOf(df.format(sueldo)));
            }else{
                double sueldo = vendidos * 0.08;
                lblsueldo.setText(String.valueOf(df.format(sueldo)));
            }
            if(txtentregado.getText().isEmpty() || txtgas.getText().isEmpty()){}else{
                double comision = Double.parseDouble(txtentregado.getText()) - Double.parseDouble(lblesperada.getText());
                lblcomision.setText(String.valueOf(df.format(comision)));
                double neto = Double.parseDouble(txtentregado.getText()) - (Double.parseDouble(lblcomision.getText()) + Double.parseDouble(lblsueldo.getText()) + Integer.parseInt(txtgas.getText()));
                lblneto.setText(String.valueOf(df.format(neto)));
            }
        }
    }//GEN-LAST:event_txtsalidaKeyReleased

    private void txtsalidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsalidaKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || txtsalida.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_txtsalidaKeyTyped

    private void txtdevueltosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdevueltosKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || txtdevueltos.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_txtdevueltosKeyTyped

    private void txtdevueltosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdevueltosKeyReleased
        if ("".equals(txtdevueltos.getText()) || "".equals(txtsalida.getText())) {
            lblvendidos.setText("0");
            lblesperada.setText("0");
        } else {
            int vendidos = Integer.parseInt(txtsalida.getText()) - Integer.parseInt(txtdevueltos.getText());
            lblvendidos.setText(String.valueOf(vendidos));
            double esperado = Integer.parseInt(lblvendidos.getText()) * 0.83;
            lblesperada.setText(String.valueOf(df.format(esperado)));
            if(vendidos > 115){
                double sueldo = vendidos * 0.08;
                lblsueldo.setText(String.valueOf(df.format(sueldo)));
            }else{
                double sueldo = vendidos * 0.08;
                lblsueldo.setText(String.valueOf(df.format(sueldo)));
            }
            if(txtentregado.getText().isEmpty() || txtgas.getText().isEmpty()){}else{
                double comision = Double.parseDouble(txtentregado.getText()) - Double.parseDouble(lblesperada.getText());
                lblcomision.setText(String.valueOf(df.format(comision)));
                double neto = Double.parseDouble(txtentregado.getText()) - (Double.parseDouble(lblcomision.getText()) + Double.parseDouble(lblsueldo.getText()) + Integer.parseInt(txtgas.getText()));
                lblneto.setText(String.valueOf(df.format(neto)));
            }
        }
    }//GEN-LAST:event_txtdevueltosKeyReleased

    private void txtentregadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtentregadoKeyReleased
        if ("".equals(txtentregado.getText())) {
            lblestado.setText("");
            lblcomision.setText("0");
        } else if (Double.parseDouble(txtentregado.getText()) >= Double.parseDouble(lblesperada.getText())) {
            lblestado.setText("Todo en orden");
            double comision = Double.parseDouble(txtentregado.getText()) - Double.parseDouble(lblesperada.getText());
            lblcomision.setText(String.valueOf(df.format(comision)));
        } else {
            lblestado.setText("Error");
            double comision = Double.parseDouble(txtentregado.getText()) - Double.parseDouble(lblesperada.getText());
            lblcomision.setText(String.valueOf(df.format(comision)));
        }
        if("".equals(txtentregado.getText()) || "".equals(txtgas.getText())){
            lblneto.setText("0");
        }else{
            double neto = Double.parseDouble(txtentregado.getText()) - (Double.parseDouble(lblcomision.getText()) + Double.parseDouble(lblsueldo.getText()) + Integer.parseInt(txtgas.getText()));
            lblneto.setText(String.valueOf(df.format(neto)));
        }
    }//GEN-LAST:event_txtentregadoKeyReleased

    private void txtentregadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtentregadoKeyTyped
        try {
            if (!Character.isDigit(evt.getKeyChar()) && !(evt.getKeyChar() == '.') || txtentregado.getText().length() >= 7) {
                evt.consume();
            }
            Double.parseDouble(txtentregado.getText() + evt.getKeyChar());
        } catch (NumberFormatException e) {
            evt.consume();
        }
    }//GEN-LAST:event_txtentregadoKeyTyped

    private void txtentregadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtentregadoFocusLost
        if (txtentregado.getText().isEmpty()) {
        } else {
            String precio = df.format(Double.parseDouble(txtentregado.getText()));
            precio = precio.replaceAll(",", ".");
            try {
                txtentregado.setText(precio);
            } catch (NumberFormatException e) {
                txtentregado.setText(null);
            }
        }
    }//GEN-LAST:event_txtentregadoFocusLost

    private void txtgasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgasKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || txtgas.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_txtgasKeyTyped

    private void txtgasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgasKeyReleased
        if ("".equals(txtgas.getText()) || "".equals(txtentregado.getText())) {
            lblneto.setText("0");
        } else {
            double comision = Double.parseDouble(txtentregado.getText()) - Double.parseDouble(lblesperada.getText());
            lblcomision.setText(String.valueOf(df.format(comision)));
            double neto = Double.parseDouble(txtentregado.getText()) - (Double.parseDouble(lblcomision.getText()) + Double.parseDouble(lblsueldo.getText()) + Integer.parseInt(txtgas.getText()));
            lblneto.setText(String.valueOf(df.format(neto)));
        }
        
    }//GEN-LAST:event_txtgasKeyReleased

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        bloquear();
        limpiar();
        tablaruta.setModel(new DefaultTableModel());
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if (cmbempleados.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "¡Debes seleccionar un empleado!", "AVISO", JOptionPane.CANCEL_OPTION);
        } else if (cmbrecibido.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "¿Quién ha recibido la venta?", "AVISO", JOptionPane.CANCEL_OPTION);
        } else if (txtsalida.getText().isEmpty() || txtdevueltos.getText().isEmpty() || txtentregado.getText().isEmpty() || txtgas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡No puedes dejar campos en blanco!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if(Double.parseDouble(lblvendidos.getText()) < 0 || Double.parseDouble(lblneto.getText()) < 0 || Double.parseDouble(lblcomision.getText()) < 0 || Double.parseDouble(lblsueldo.getText()) < 0){
            JOptionPane.showMessageDialog(this, "¡Ha ingreso datos incoherentes!", "AVISO", JOptionPane.CANCEL_OPTION);
        } else {
            try {
                st = cn.prepareStatement("SELECT id_emp FROM empleados WHERE nom_emp = ?");
                st.setString(1, cmbempleados.getSelectedItem().toString());
                ResultSet rs = st.executeQuery();
                if (rs.next()) {
                    String empleado = rs.getString(1);
                    st = cn.prepareStatement("SELECT id_admin FROM administradores WHERE nom_admin = ?");
                    st.setString(1, cmbrecibido.getSelectedItem().toString());
                    ResultSet rs2 = st.executeQuery();
                    if (rs2.next()) {
                        String admin = rs2.getString(1);
                        if (txtcomentarios.getText().isEmpty()) {
                            st = cn.prepareStatement("INSERT INTO rutas(fecha_ruta, cant_salida_ruta, devol_ruta, vendidos_ruta, "
                                    + "cantidad_esp_ruta, entregado_ruta, ganancia_vend_ruta, sueldo_vend_ruta, gas_ruta, saldo_neto_ruta, "
                                    + "coment_ruta, id_admin, id_emp) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                            java.sql.Date sqlFecha = new java.sql.Date(cmbfecha.getDate().getTime());
                            st.setDate(1, sqlFecha);
                            st.setInt(2, Integer.parseInt(txtsalida.getText()));
                            st.setInt(3, Integer.parseInt(txtdevueltos.getText()));
                            st.setInt(4, Integer.parseInt(lblvendidos.getText()));
                            st.setDouble(5, Double.parseDouble(lblesperada.getText()));
                            st.setDouble(6, Double.parseDouble(txtentregado.getText()));
                            st.setDouble(7, Double.parseDouble(lblcomision.getText()));
                            st.setDouble(8, Double.parseDouble(lblsueldo.getText()));
                            st.setInt(9, Integer.parseInt(txtgas.getText()));
                            st.setDouble(10, Double.parseDouble(lblneto.getText()));
                            st.setString(11, "No hay comentarios.");
                            st.setInt(12, Integer.parseInt(admin));
                            st.setInt(13, Integer.parseInt(empleado));
                            st.executeUpdate();
                            JOptionPane.showMessageDialog(rootPane, "Datos guardados con éxito");
                            bloquear();
                            MostrarDatos(Integer.parseInt(txtempleado.getText()));
                            limpiar();
                            tablaruta.setModel(new DefaultTableModel());
                        }else{
                            st = cn.prepareStatement("INSERT INTO rutas(fecha_ruta, cant_salida_ruta, devol_ruta, vendidos_ruta, "
                                    + "cantidad_esp_ruta, entregado_ruta, ganancia_vend_ruta, sueldo_vend_ruta, gas_ruta, saldo_neto_ruta, "
                                    + "coment_ruta, id_admin, id_emp) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                            java.sql.Date sqlFecha = new java.sql.Date(cmbfecha.getDate().getTime());
                            st.setDate(1, sqlFecha);
                            st.setInt(2, Integer.parseInt(txtsalida.getText()));
                            st.setInt(3, Integer.parseInt(txtdevueltos.getText()));
                            st.setInt(4, Integer.parseInt(lblvendidos.getText()));
                            st.setDouble(5, Double.parseDouble(lblesperada.getText()));
                            st.setDouble(6, Double.parseDouble(txtentregado.getText()));
                            st.setDouble(7, Double.parseDouble(lblcomision.getText()));
                            st.setDouble(8, Double.parseDouble(lblsueldo.getText()));
                            st.setInt(9, Integer.parseInt(txtgas.getText()));
                            st.setDouble(10, Double.parseDouble(lblneto.getText()));
                            st.setString(11, txtcomentarios.getText());
                            st.setInt(12, Integer.parseInt(admin));
                            st.setInt(13, Integer.parseInt(empleado));
                            st.executeUpdate();
                            JOptionPane.showMessageDialog(rootPane, "Datos guardados con éxito");
                            bloquear();
                            MostrarDatos(Integer.parseInt(txtempleado.getText()));
                            limpiar();
                            tablaruta.setModel(new DefaultTableModel());
                        }
                    }
                }
            } catch (SQLException | NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        if (cmbempleados.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un empleado para realizar la consulta", "AVISO", JOptionPane.CANCEL_OPTION);
        } else {
            MostrarDatos(Integer.parseInt(txtempleado.getText()));
        }
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if("".equals(txtcodigo.getText())){
            JOptionPane.showMessageDialog(this, "¡Debes realizar y seleccionar una consulta para eliminar!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else{
            try {
                st = cn.prepareStatement("DELETE FROM rutas WHERE id_ruta = ?");
                st.setInt(1, Integer.parseInt(txtcodigo.getText()));
                if(JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro que desea eliminar estos datos?" + "\n¡Ya no podrán ser recuperados!", "Confirmación", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "Datos eliminados con éxito");
                    MostrarDatos(Integer.parseInt(txtempleado.getText()));
                    bloquear();
                    limpiar();
                    cmbempleados.setSelectedIndex(-1);
                    tablaruta.setModel(new DefaultTableModel());
                }
            } catch (SQLException | NumberFormatException | HeadlessException e) {JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void tablarutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablarutaMouseClicked
        try {
            txtcodigo.setText(tablaruta.getValueAt(tablaruta.getSelectedRow(), 0).toString());
            SimpleDateFormat Formateador = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date fecha = Formateador.parse(tablaruta.getValueAt(tablaruta.getSelectedRow(), 1).toString());
            cmbfecha.setSelectedIndex(-1);
            cmbfecha.setDate(fecha);
            txtsalida.setText(tablaruta.getValueAt(tablaruta.getSelectedRow(), 2).toString());
            txtdevueltos.setText(tablaruta.getValueAt(tablaruta.getSelectedRow(), 3).toString());
            txtentregado.setText(tablaruta.getValueAt(tablaruta.getSelectedRow(), 6).toString());
            txtgas.setText(tablaruta.getValueAt(tablaruta.getSelectedRow(), 9).toString());
            cmbrecibido.setSelectedItem(tablaruta.getValueAt(tablaruta.getSelectedRow(), 11));
            lblvendidos.setText(tablaruta.getValueAt(tablaruta.getSelectedRow(), 4).toString());
            lblesperada.setText(tablaruta.getValueAt(tablaruta.getSelectedRow(), 5).toString());
            lblcomision.setText(tablaruta.getValueAt(tablaruta.getSelectedRow(), 7).toString());
            lblsueldo.setText(tablaruta.getValueAt(tablaruta.getSelectedRow(), 8).toString());
            lblneto.setText(tablaruta.getValueAt(tablaruta.getSelectedRow(), 10).toString());
            txtcomentarios.setText(tablaruta.getValueAt(tablaruta.getSelectedRow(), 12).toString());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "ERROR: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tablarutaMouseClicked

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        if("".equals(txtcodigo.getText())){
            JOptionPane.showMessageDialog(this, "¡Debes realizar una consulta y seleccionarla!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if(cmbempleados.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(this, "¡Debes seleccionar un empleado!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if(txtsalida.getText().isEmpty() || txtdevueltos.getText().isEmpty() || txtentregado.getText().isEmpty() || txtgas.getText().isEmpty() || txtcomentarios.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "¡No puedes dejar campos en blanco!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if(cmbrecibido.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(this, "¡Debes seleccionar quién lo recibió!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if(Double.parseDouble(lblvendidos.getText()) < 0 || Double.parseDouble(lblneto.getText()) < 0 || Double.parseDouble(lblcomision.getText()) < 0 || Double.parseDouble(lblsueldo.getText()) < 0){
            JOptionPane.showMessageDialog(this, "¡Ha ingreso datos incoherentes!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else{
            try {
                st = cn.prepareStatement("SELECT id_emp FROM empleados WHERE nom_emp = ?");
                st.setString(1, cmbempleados.getSelectedItem().toString());
                ResultSet rs = st.executeQuery();
                if (rs.next()) {
                    String empleado = rs.getString(1);
                    st = cn.prepareStatement("SELECT id_admin FROM administradores WHERE nom_admin = ?");
                    st.setString(1, cmbrecibido.getSelectedItem().toString());
                    ResultSet rs2 = st.executeQuery();
                    if (rs2.next()) {
                        String admin = rs2.getString(1);
                        st = cn.prepareStatement("UPDATE rutas SET fecha_ruta = ?, cant_salida_ruta = ?, devol_ruta = ?, vendidos_ruta = ?, "
                                + "cantidad_esp_ruta = ?, entregado_ruta = ?, ganancia_vend_ruta = ?, sueldo_vend_ruta = ?, gas_ruta = ?, saldo_neto_ruta = ?, "
                                + "coment_ruta = ?, id_admin = ?, id_emp = ? WHERE id_ruta = ?");
                        java.sql.Date sqlFecha = new java.sql.Date(cmbfecha.getDate().getTime());
                        st.setDate(1, sqlFecha);
                        st.setInt(2, Integer.parseInt(txtsalida.getText()));
                        st.setInt(3, Integer.parseInt(txtdevueltos.getText()));
                        st.setInt(4, Integer.parseInt(lblvendidos.getText()));
                        st.setDouble(5, Double.parseDouble(lblesperada.getText()));
                        st.setDouble(6, Double.parseDouble(txtentregado.getText()));
                        st.setDouble(7, Double.parseDouble(lblcomision.getText()));
                        st.setDouble(8, Double.parseDouble(lblsueldo.getText()));
                        st.setInt(9, Integer.parseInt(txtgas.getText()));
                        st.setDouble(10, Double.parseDouble(lblneto.getText()));
                        st.setString(11, txtcomentarios.getText());
                        st.setInt(12, Integer.parseInt(admin));
                        st.setInt(13, Integer.parseInt(empleado));
                        st.setInt(14, Integer.parseInt(txtcodigo.getText()));
                        st.executeUpdate();
                        JOptionPane.showMessageDialog(rootPane, "Datos modificados con éxito");
                        MostrarDatos(Integer.parseInt(txtempleado.getText()));
                        limpiar2();
                    }
                }
            } catch (SQLException | NumberFormatException | HeadlessException e) {JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void txtcomentariosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcomentariosKeyTyped
        if (txtcomentarios.getText().length() >= 195) {
            evt.consume();
        } 
    }//GEN-LAST:event_txtcomentariosKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(null, "ATENCIÓN" + "\nLe recomendamos que verifique si ha ingresado correctamente los datos de este día" + "\nDicho esto, ¿Desea cerrar la ventana?", "AVISO", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
        }else{
            dispose();
            frmRuta obj = new frmRuta(null, true);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    public void CargarEmpleados() {
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT nom_emp FROM empleados ORDER BY nom_emp");
            cmbempleados.removeAllItems();
            while (rs.next()) {
                cmbempleados.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "ERROR: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void CargarAdmin() {
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT nom_admin FROM administradores ORDER BY nom_admin");
            cmbrecibido.removeAllItems();
            while (rs.next()) {
                cmbrecibido.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "ERROR: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void bloquear() {
        cmbfecha.setEnabled(false);
        cmbrecibido.setEnabled(false);
        txtsalida.setEnabled(false);
        txtdevueltos.setEnabled(false);
        txtentregado.setEnabled(false);
        txtgas.setEnabled(false);
        lblvendidos.setText("0");
        lblesperada.setText("0");
        lblestado.setText("");
        lblcomision.setText("0");
        lblsueldo.setText("0");
        lblneto.setText("0");
    }

    public void limpiar() {
        txtsalida.setText("");
        txtdevueltos.setText("");
        txtentregado.setText("");
        txtgas.setText("");
        txtcomentarios.setText("");
        txtcodigo.setText("");
        cmbrecibido.setSelectedIndex(-1);
        cmbempleados.setSelectedIndex(-1);
        lblvendidos.setText("0");
        lblesperada.setText("0");
        lblestado.setText("");
        lblcomision.setText("0");
        lblsueldo.setText("0");
        lblneto.setText("0");
    }
    
    public void limpiar2() {
        txtsalida.setText("");
        txtdevueltos.setText("");
        txtentregado.setText("");
        txtgas.setText("");
        txtcomentarios.setText("");
        cmbrecibido.setSelectedIndex(-1);
        lblvendidos.setText("0");
        lblesperada.setText("0");
        lblestado.setText("");
        lblcomision.setText("0");
        lblsueldo.setText("0");
        lblneto.setText("0");
    }

    private void MostrarDatos(int nombre) {
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        modelo.addColumn("Código");
        modelo.addColumn("Fecha");
        modelo.addColumn("Salida");
        modelo.addColumn("Devolvió");
        modelo.addColumn("Vendió");
        modelo.addColumn("Se esperaba");
        modelo.addColumn("Entregó");
        modelo.addColumn("Comisión");
        modelo.addColumn("Sueldo");
        modelo.addColumn("Gasolina");
        modelo.addColumn("Saldo Neto");
        modelo.addColumn("Recibido por");
        modelo.addColumn("Comentario");
        tablaruta.setModel(modelo);
        String sql = "SELECT id_ruta, fecha_ruta, cant_salida_ruta, devol_ruta, vendidos_ruta, cantidad_esp_ruta,"
                + "entregado_ruta, ganancia_vend_ruta, sueldo_vend_ruta, gas_ruta, saldo_neto_ruta, nom_admin, coment_ruta"
                + " FROM rutas r INNER JOIN empleados e INNER JOIN administradores a ON r.id_emp=e.id_emp AND r.id_admin=a.id_admin "
                + "WHERE e.id_emp = " + nombre + " ORDER BY fecha_ruta ASC";
        String[] datos = new String[13];
        try {
            Statement st2 = cn.createStatement();
            ResultSet rs = st2.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                datos[8] = rs.getString(9);
                datos[9] = rs.getString(10);
                datos[10] = rs.getString(11);
                datos[11] = rs.getString(12);
                datos[12] = rs.getString(13);
                modelo.addRow(datos);
            }
            tablaruta.setModel(modelo);
            tablaruta.getTableHeader().setReorderingAllowed(false);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "ERROR: " + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmRuta dialog = new frmRuta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JComboBox<String> cmbempleados;
    private org.freixas.jcalendar.JCalendarCombo cmbfecha;
    private javax.swing.JComboBox<String> cmbrecibido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblcomision;
    private javax.swing.JLabel lblesperada;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblneto;
    private javax.swing.JLabel lblsueldo;
    private javax.swing.JLabel lblvendidos;
    private javax.swing.JTable tablaruta;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextArea txtcomentarios;
    private javax.swing.JTextField txtdevueltos;
    private javax.swing.JTextField txtempleado;
    private javax.swing.JTextField txtentregado;
    private javax.swing.JTextField txtgas;
    private javax.swing.JTextField txtsalida;
    // End of variables declaration//GEN-END:variables
}
