/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ClsConexion;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Will Vásquez
 */
public class frmVentaPlanta extends javax.swing.JDialog {
    ClsConexion cc = new ClsConexion();
    Connection cn = cc.conectar();
    private PreparedStatement st;
    DefaultTableModel modelo;
    DecimalFormatSymbols simbolos = DecimalFormatSymbols.getInstance(Locale.ENGLISH);
    DecimalFormat df = new DecimalFormat("0.00", simbolos);

    /**
     * Creates new form frmVentaPlanta
     */
    public frmVentaPlanta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Gestor venta en planta");
        getContentPane().setBackground(Color.DARK_GRAY);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcodigo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbfecha = new org.freixas.jcalendar.JCalendarCombo();
        jLabel2 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbtipo = new javax.swing.JComboBox<>();
        txttipo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfardos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmonto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbestado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbrecibido = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladetalles = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtcomentarios = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablavdiaria = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cliente:");

        txtcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtclienteKeyTyped(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo:");

        cmbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Promoción", "Dólar", "Mayorista 1", "Mayorista 2", "Especial", "Súper Especial", "Otro" }));
        cmbtipo.setSelectedIndex(-1);
        cmbtipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbtipoItemStateChanged(evt);
            }
        });

        txttipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttipoKeyTyped(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fardos:");

        txtfardos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfardosActionPerformed(evt);
            }
        });
        txtfardos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfardosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfardosKeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Monto venta ($):");

        txtmonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmontoFocusLost(evt);
            }
        });
        txtmonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmontoKeyTyped(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estado:");

        cmbestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cancelado", "Pendiente" }));
        cmbestado.setSelectedIndex(-1);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Recibido por:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtcliente)
                    .addComponent(cmbtipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txttipo)
                    .addComponent(txtfardos)
                    .addComponent(txtmonto)
                    .addComponent(cmbestado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbrecibido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtfardos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbrecibido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Detalles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        tabladetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Promoción", "3 por 2.50"},
                {"Dólar", "Su nombre lo dice"},
                {"Mayorista 1", "1 por 0.70"},
                {"Mayorista 2", "1 por 0.75"},
                {"Especial", "1 por 0.65"},
                {"Súper Especial", "1 por 0.60"}
            },
            new String [] {
                "Tipo", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabladetalles);
        if (tabladetalles.getColumnModel().getColumnCount() > 0) {
            tabladetalles.getColumnModel().getColumn(0).setResizable(false);
            tabladetalles.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Comentarios:");

        txtcomentarios.setColumns(20);
        txtcomentarios.setLineWrap(true);
        txtcomentarios.setRows(2);
        txtcomentarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcomentariosKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtcomentarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/agregar.png"))); // NOI18N
        btnguardar.setText("Guardar datos");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/edit.png"))); // NOI18N
        btnmodificar.setText("Modificar datos");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btnconsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/consultar.png"))); // NOI18N
        btnconsultar.setText("Consultar datos");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/eliminar.png"))); // NOI18N
        btneliminar.setText("Eliminar datos");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/limpiar.png"))); // NOI18N
        btnlimpiar.setText("Limpiar datos");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnconsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnguardar)
                .addGap(18, 18, 18)
                .addComponent(btnmodificar)
                .addGap(18, 18, 18)
                .addComponent(btnconsultar)
                .addGap(18, 18, 18)
                .addComponent(btneliminar)
                .addGap(18, 18, 18)
                .addComponent(btnlimpiar)
                .addGap(18, 18, 18)
                .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tablavdiaria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablavdiaria.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablavdiaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablavdiariaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablavdiaria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txttipo.setEnabled(false);
        txtmonto.setEnabled(false);
        CargarAdmin();
        cmbrecibido.setSelectedIndex(-1);
    }//GEN-LAST:event_formWindowOpened

    private void cmbtipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbtipoItemStateChanged
        switch (cmbtipo.getSelectedIndex()) {
            case 0:
                txttipo.setText("");
                txttipo.setEnabled(false);
                txtmonto.setEnabled(false);
                if(!(txtfardos.getText().isEmpty())){
                    double division = Double.parseDouble(txtfardos.getText()) / 3;
                    double monto = division * 2.5;
                    txtmonto.setText(String.valueOf(df.format(monto)));
                }   break;
            case 1:
                txttipo.setText("");
                txttipo.setEnabled(false);
                txtmonto.setEnabled(false);
                if(!(txtfardos.getText().isEmpty())){
                    double monto = Double.parseDouble(txtfardos.getText()) * 1.00;
                    txtmonto.setText(String.valueOf(df.format(monto)));
                }   break;
            case 2:
                txttipo.setText("");
                txttipo.setEnabled(false);
                txtmonto.setEnabled(false);
                if(!(txtfardos.getText().isEmpty())){
                    double monto = Double.parseDouble(txtfardos.getText()) * 0.70;
                    txtmonto.setText(String.valueOf(df.format(monto)));
                }   break;
            case 3:
                txttipo.setText("");
                txttipo.setEnabled(false);
                txtmonto.setEnabled(false);
                if(!(txtfardos.getText().isEmpty())){
                    double monto = Double.parseDouble(txtfardos.getText()) * 0.75;
                    txtmonto.setText(String.valueOf(df.format(monto)));
                }   break;
            case 4:
                txttipo.setText("");
                txttipo.setEnabled(false);
                txtmonto.setEnabled(false);
                if(!(txtfardos.getText().isEmpty())){
                    double monto = Double.parseDouble(txtfardos.getText()) * 0.65;
                    txtmonto.setText(String.valueOf(df.format(monto)));
                }   break;
            case 5:
                txttipo.setText("");
                txttipo.setEnabled(false);
                txtmonto.setEnabled(false);
                if(!(txtfardos.getText().isEmpty())){
                    double monto = Double.parseDouble(txtfardos.getText()) * 0.60;
                    txtmonto.setText(String.valueOf(df.format(monto)));
                }   break;
            case 6:
                txttipo.setEnabled(true);
                txtmonto.setEnabled(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cmbtipoItemStateChanged

    private void txtfardosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfardosKeyReleased
        if(!(txtfardos.getText().isEmpty())){
            switch (cmbtipo.getSelectedIndex()) {
            case 0:
                if(!(txtfardos.getText().isEmpty())){
                    double division = Double.parseDouble(txtfardos.getText()) / 3;
                    double monto = division * 2.5;
                    txtmonto.setText(String.valueOf(df.format(monto)));
                }   break;
            case 1:
                if(!(txtfardos.getText().isEmpty())){
                    double monto = Double.parseDouble(txtfardos.getText()) * 1.00;
                    txtmonto.setText(String.valueOf(df.format(monto)));
                }   break;
            case 2:
                if(!(txtfardos.getText().isEmpty())){
                    double monto = Double.parseDouble(txtfardos.getText()) * 0.70;
                    txtmonto.setText(String.valueOf(df.format(monto)));
                }   break;
            case 3:
                if(!(txtfardos.getText().isEmpty())){
                    double monto = Double.parseDouble(txtfardos.getText()) * 0.75;
                    txtmonto.setText(String.valueOf(df.format(monto)));
                }   break;
            case 4:
                if(!(txtfardos.getText().isEmpty())){
                    double monto = Double.parseDouble(txtfardos.getText()) * 0.65;
                    txtmonto.setText(String.valueOf(df.format(monto)));
                }   break;
            case 5:
                if(!(txtfardos.getText().isEmpty())){
                    double monto = Double.parseDouble(txtfardos.getText()) * 0.60;
                    txtmonto.setText(String.valueOf(df.format(monto)));
                }   break;
            default:
                break;
        }
        }else{
            txtmonto.setText("0.0");
        }
    }//GEN-LAST:event_txtfardosKeyReleased

    private void txtmontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontoKeyTyped
        try {
            if (!Character.isDigit(evt.getKeyChar()) && !(evt.getKeyChar() == '.') || txtmonto.getText().length() >= 7) {
                evt.consume();
            }
            Double.parseDouble(txtmonto.getText() + evt.getKeyChar());
        } catch (NumberFormatException e) {
            evt.consume();
        }
    }//GEN-LAST:event_txtmontoKeyTyped

    private void txtmontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmontoFocusLost
        if (txtmonto.getText().isEmpty()) {
        } else {
            String precio = df.format(Double.parseDouble(txtmonto.getText()));
            precio = precio.replaceAll(",", ".");
            try {
                txtmonto.setText(precio);
            } catch (NumberFormatException e) {
                txtmonto.setText(null);
            }
        }
    }//GEN-LAST:event_txtmontoFocusLost

    private void txtfardosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfardosKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || txtfardos.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_txtfardosKeyTyped

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        limpiar();
        tablavdiaria.setModel(new DefaultTableModel());
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        MostrarDatos();
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if(txtcliente.getText().isEmpty() || txtfardos.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "¡No puedes dejar campos en blanco!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if(cmbtipo.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(this, "¡Debe seleccionar un tipo!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if(cmbestado.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(this, "¡Debes seleccionar un estado!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if(cmbrecibido.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(this, "¿Quién ha recibido la venta?", "AVISO", JOptionPane.CANCEL_OPTION);
        }else{
            try {
                st = cn.prepareStatement("SELECT id_admin FROM administradores WHERE nom_admin = ?");
                st.setString(1, cmbrecibido.getSelectedItem().toString());
                ResultSet rs2 = st.executeQuery();
                if (rs2.next()) {
                    String admin = rs2.getString(1);
                    if((!txttipo.getText().isEmpty()) || cmbtipo.getSelectedItem() == "Otro"){
                        if(txttipo.getText().isEmpty() || txtmonto.getText().isEmpty()){
                            JOptionPane.showMessageDialog(this, "¡Debes detallar el tipo de venta y digitar el monto!", "AVISO", JOptionPane.CANCEL_OPTION);
                        }else{
                            st = cn.prepareStatement("INSERT INTO ventaplanta(fecha_ventap, cliente_ventap, tipo_ventap, "
                                    + "fardos_vendidos_ventap, monto_ventap, estado_ventap, coment_vplanta, id_admin) "
                                    + "VALUES(?, ?, ?, ?, ?, ?, ?, ?)");
                            java.sql.Date sqlFecha = new java.sql.Date(cmbfecha.getDate().getTime());
                            st.setDate(1, sqlFecha);
                            st.setString(2, txtcliente.getText());
                            st.setString(3, txttipo.getText());
                            st.setInt(4, Integer.parseInt(txtfardos.getText()));
                            st.setDouble(5, Double.parseDouble(txtmonto.getText()));
                            st.setString(6, cmbestado.getSelectedItem().toString());
                            if(!(txtcomentarios.getText().isEmpty())){
                                st.setString(7, txtcomentarios.getText());
                            }else{st.setString(7, "No hay comentarios.");}
                            st.setInt(8, Integer.parseInt(admin));
                            st.executeUpdate();
                            JOptionPane.showMessageDialog(rootPane, "Datos guardados con éxito");
                            limpiar();
                            MostrarDatos();
                        }
                    }else{
                        st = cn.prepareStatement("INSERT INTO ventaplanta(fecha_ventap, cliente_ventap, tipo_ventap, "
                                + "fardos_vendidos_ventap, monto_ventap, estado_ventap, coment_vplanta, id_admin) "
                                + "VALUES(?, ?, ?, ?, ?, ?, ?, ?)");
                        java.sql.Date sqlFecha = new java.sql.Date(cmbfecha.getDate().getTime());
                        st.setDate(1, sqlFecha);
                        st.setString(2, txtcliente.getText());
                        st.setString(3, cmbtipo.getSelectedItem().toString());
                        st.setInt(4, Integer.parseInt(txtfardos.getText()));
                        st.setDouble(5, Double.parseDouble(txtmonto.getText()));
                        st.setString(6, cmbestado.getSelectedItem().toString());
                        if(!(txtcomentarios.getText().isEmpty())){
                            st.setString(7, txtcomentarios.getText());
                        }else{st.setString(7, "No hay comentarios.");}
                        st.setInt(8, Integer.parseInt(admin));
                        st.executeUpdate();
                        JOptionPane.showMessageDialog(rootPane, "Datos guardados con éxito");
                        limpiar();
                        MostrarDatos();
                    }
                }
            } catch (SQLException | NumberFormatException e) {JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void tablavdiariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablavdiariaMouseClicked
        try {
            txtcodigo.setText(tablavdiaria.getValueAt(tablavdiaria.getSelectedRow(), 0).toString());
            SimpleDateFormat Formateador = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date fecha = Formateador.parse(tablavdiaria.getValueAt(tablavdiaria.getSelectedRow(), 1).toString());
            cmbfecha.setSelectedIndex(-1);
            cmbfecha.setDate(fecha);
            txtcliente.setText(tablavdiaria.getValueAt(tablavdiaria.getSelectedRow(), 2).toString());
            cmbtipo.setSelectedItem(tablavdiaria.getValueAt(tablavdiaria.getSelectedRow(), 3));
            txttipo.setText(tablavdiaria.getValueAt(tablavdiaria.getSelectedRow(), 3).toString());
            txtfardos.setText(tablavdiaria.getValueAt(tablavdiaria.getSelectedRow(), 4).toString());
            txtmonto.setText(tablavdiaria.getValueAt(tablavdiaria.getSelectedRow(), 5).toString());
            cmbestado.setSelectedItem(tablavdiaria.getValueAt(tablavdiaria.getSelectedRow(), 6));
            cmbrecibido.setSelectedItem(tablavdiaria.getValueAt(tablavdiaria.getSelectedRow(), 7));
            txtcomentarios.setText(tablavdiaria.getValueAt(tablavdiaria.getSelectedRow(), 8).toString());
        } catch (Exception e) {JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_tablavdiariaMouseClicked

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        if("".equals(txtcodigo.getText())){
            JOptionPane.showMessageDialog(this, "¡Debes realizar y seleccionar una consulta para eliminar!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else if(txtcliente.getText().isEmpty() || txtfardos.getText().isEmpty() || txtmonto.getText().isEmpty() || txtcomentarios.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "¡No puedes dejar campos en blanco!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else{
            try {
                st = cn.prepareStatement("SELECT id_admin FROM administradores WHERE nom_admin = ?");
                st.setString(1, cmbrecibido.getSelectedItem().toString());
                ResultSet rs2 = st.executeQuery();
                if (rs2.next()) {
                    String admin = rs2.getString(1);
                    if((!txttipo.getText().isEmpty()) || cmbtipo.getSelectedItem() == "Otro"){
                        if(txttipo.getText().isEmpty() || txtmonto.getText().isEmpty()){
                            JOptionPane.showMessageDialog(this, "¡Debes detallar el tipo de venta y digitar el monto!", "AVISO", JOptionPane.CANCEL_OPTION);
                        }else{
                            st = cn.prepareStatement("UPDATE ventaplanta SET fecha_ventap = ?, cliente_ventap = ?, tipo_ventap = ?, "
                                    + "fardos_vendidos_ventap = ?, monto_ventap = ?, estado_ventap = ?, coment_vplanta = ?, id_admin = ? "
                                    + "WHERE id_ventap = ?");
                            java.sql.Date sqlFecha = new java.sql.Date(cmbfecha.getDate().getTime());
                            st.setDate(1, sqlFecha);
                            st.setString(2, txtcliente.getText());
                            st.setString(3, txttipo.getText());
                            st.setInt(4, Integer.parseInt(txtfardos.getText()));
                            st.setDouble(5, Double.parseDouble(txtmonto.getText()));
                            st.setString(6, cmbestado.getSelectedItem().toString());
                            st.setString(7, txtcomentarios.getText());
                            st.setInt(8, Integer.parseInt(admin));
                            st.setInt(9, Integer.parseInt(txtcodigo.getText()));
                            st.executeUpdate();
                            JOptionPane.showMessageDialog(rootPane, "Datos modificados con éxito");
                            limpiar();
                            MostrarDatos();
                        }
                    }else{
                        st = cn.prepareStatement("UPDATE ventaplanta SET fecha_ventap = ?, cliente_ventap = ?, tipo_ventap = ?, "
                                + "fardos_vendidos_ventap = ?, monto_ventap = ?, estado_ventap = ?, coment_vplanta = ?, id_admin = ? "
                                + "WHERE id_ventap = ?");
                        java.sql.Date sqlFecha = new java.sql.Date(cmbfecha.getDate().getTime());
                        st.setDate(1, sqlFecha);
                        st.setString(2, txtcliente.getText());
                        st.setString(3, cmbtipo.getSelectedItem().toString());
                        st.setInt(4, Integer.parseInt(txtfardos.getText()));
                        st.setDouble(5, Double.parseDouble(txtmonto.getText()));
                        st.setString(6, cmbestado.getSelectedItem().toString());
                        st.setString(7, txtcomentarios.getText());
                        st.setInt(8, Integer.parseInt(admin));
                        st.setInt(9, Integer.parseInt(txtcodigo.getText()));
                        st.executeUpdate();
                        JOptionPane.showMessageDialog(rootPane, "Datos modificados con éxito");
                        limpiar();
                        MostrarDatos();
                    }
                }
            } catch (SQLException | NumberFormatException | HeadlessException e) {JOptionPane.showMessageDialog(this, "Error: " + e, "ERORR", JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if("".equals(txtcodigo.getText())){
            JOptionPane.showMessageDialog(this, "¡Debes realizar y seleccionar una consulta para eliminar!", "AVISO", JOptionPane.CANCEL_OPTION);
        }else{
            try {
                st = cn.prepareStatement("DELETE FROM ventaplanta WHERE id_ventap = ?");
                st.setInt(1, Integer.parseInt(txtcodigo.getText()));
                if(JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro que desea eliminar estos datos?" + "\n¡Ya no podrán ser recuperados!", "Confirmación", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "Datos eliminados con éxito");
                    MostrarDatos();
                    limpiar();
                }
            } catch (SQLException | NumberFormatException | HeadlessException e) {JOptionPane.showMessageDialog(this, "ERROR: " + e, "Error", JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtcomentariosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcomentariosKeyTyped
        if (txtcomentarios.getText().length() >= 195) {
            evt.consume();
        }
    }//GEN-LAST:event_txtcomentariosKeyTyped

    private void txtclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclienteKeyTyped
        if (txtcliente.getText().length() >= 65) {
            evt.consume();
        }
    }//GEN-LAST:event_txtclienteKeyTyped

    private void txttipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttipoKeyTyped
        if (txttipo.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_txttipoKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(null, "ATENCIÓN" + "\nLe recomendamos que verifique si ha ingresado correctamente los datos de este día" + "\nDicho esto, ¿Desea cerrar la ventana?", "AVISO", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
        }else{
            dispose();
            frmVentaPlanta obj = new frmVentaPlanta(null, true);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void txtfardosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfardosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfardosActionPerformed

    public void CargarAdmin() {
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT nom_admin FROM administradores ORDER BY nom_admin");
            cmbrecibido.removeAllItems();
            while (rs.next()) {
                cmbrecibido.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "ERROR: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void MostrarDatos(){
        modelo= new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        modelo.addColumn("Código");
        modelo.addColumn("Fecha");
        modelo.addColumn("Cliente");
        modelo.addColumn("Tipo");
        modelo.addColumn("Fardos");
        modelo.addColumn("Monto");
        modelo.addColumn("Estado");
        modelo.addColumn("Recibido por");
        modelo.addColumn("Comentarios");
        tablavdiaria.setModel(modelo);
        String sql = "SELECT id_ventap, fecha_ventap, cliente_ventap, tipo_ventap, fardos_vendidos_ventap, monto_ventap, estado_ventap, nom_admin, coment_vplanta FROM ventaplanta v INNER JOIN administradores a ON v.id_admin=a.id_admin ORDER BY fecha_ventap ASC";
        String []datos = new String [9];
        try {
            Statement st2 = cn.createStatement();
            ResultSet rs = st2.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                modelo.addRow(datos);
            }
            tablavdiaria.setModel(modelo);
            tablavdiaria.getTableHeader().setReorderingAllowed(false) ;
            TableColumnModel columnModel = tablavdiaria.getColumnModel();
            for (int i = 0; i < columnModel.getColumnCount(); i++) {
                columnModel.getColumn(i).setPreferredWidth(120);
            }
        } catch (SQLException ex) {JOptionPane.showMessageDialog(rootPane, "ERROR: " + ex, "ERROR", JOptionPane.ERROR_MESSAGE);}
    }
    
    private void limpiar(){
        txtcliente.setText("");
        cmbtipo.setSelectedIndex(-1);
        txttipo.setText("");
        txtfardos.setText("");
        txtmonto.setText("0.0");
        cmbestado.setSelectedIndex(-1);
        cmbrecibido.setSelectedIndex(-1);
        txtcomentarios.setText("");
        txtcodigo.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVentaPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVentaPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVentaPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVentaPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmVentaPlanta dialog = new frmVentaPlanta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JComboBox<String> cmbestado;
    private org.freixas.jcalendar.JCalendarCombo cmbfecha;
    private javax.swing.JComboBox<String> cmbrecibido;
    private javax.swing.JComboBox<String> cmbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private javax.swing.JTable tabladetalles;
    private javax.swing.JTable tablavdiaria;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextArea txtcomentarios;
    private javax.swing.JTextField txtfardos;
    private javax.swing.JTextField txtmonto;
    private javax.swing.JTextField txttipo;
    // End of variables declaration//GEN-END:variables
}
